In [10]:
import pandas as pd

In [11]:
from utils.data_manipulations import *

In [12]:
metallican_path = r'C:\Users\mp_ma\OneDrive - polymtl\POST_DOC\CODE\metallican_db'

# Import MetalliCan tables

In [13]:
main_table = pd.read_csv(metallican_path + r'\database\CSV\main_table.csv')
production_table = pd.read_csv(metallican_path + r'\database\CSV\production_table.csv')
tech_attributes_table = pd.read_csv(metallican_path + r'\database\CSV\tech_attributes_table.csv')
env_table = pd.read_csv(metallican_path + r'\database\CSV\environmental_flows_table.csv')
technosphere_table = pd.read_csv(metallican_path + r'\database\CSV\materials_energy_table.csv')
archetypes_table = pd.read_csv(metallican_path + r'\database\CSV\archetypes_table.csv')
land_table = pd.read_csv(metallican_path + r'\database\CSV\land_occupation_table.csv')
intensity_table = pd.read_csv(metallican_path + r'\database\CSV\intensity_table.csv')
waste_table = pd.read_table(metallican_path + r'\database\CSV\waste_table.csv', sep=',')
substances_table = pd.read_csv(metallican_path + r'\database\CSV\substances_table.csv')
#npv_table = pd.read_csv(metallican_path + r'\database\CSV\npv_table.csv')

In [14]:
intensity_table_nrj = intensity_table[intensity_table['type'] == 'Energy']
intensity_table_nrj = intensity_table_nrj[~intensity_table_nrj['intensity_id'].str.startswith('INT-CMP')]

In [15]:
# Let's remove ClimateTRACE data from production and env tables
production_table = production_table[~production_table['source_id'].str.startswith('https://github.com/climatetracecoalition/methodology-documents/tree/main/2024/Mineral%20Extraction')]
env_table = env_table[~env_table['source_id'].str.startswith('https://github.com/climatetracecoalition/methodology-documents/tree/main/2024/Mineral%20Extraction')]

In [16]:
production_table = merge_main_and_group(production_table, main_table, cols_to_add=['facility_name', 'facility_group_name'])
ta_table = merge_main_and_group(tech_attributes_table, main_table, cols_to_add=['facility_name', 'facility_group_name'])

In [17]:
ta_table = add_site_id(ta_table)

In [23]:
production_table.to_csv(r'data\MetalliCan\pre_cleaned_data\production_table.csv', index=False, encoding='utf-8-sig')
ta_table.to_csv(r'data\MetalliCan\pre_cleaned_data\ta_table.csv', index=False, encoding='utf-8-sig')

In [24]:
ghg_table = env_table[env_table['substance_id'] == 'NA - GHG']
# Remove scope 2 and scope 3 emissions from ghg_table, they are in the comment column
ghg_table = ghg_table[~ghg_table['comment'].str.contains('scope1+2', case=False, na=False)]
ghg_table = ghg_table[~ghg_table['comment'].str.contains('scope2', case=False, na=False)]
ghg_table = ghg_table[~ghg_table['comment'].str.contains('scope3', case=False, na=False)]

In [25]:
#ids_energy = set(energy_table[['main_id', 'facility_group_id']].apply(tuple, axis=1))
#ids_material = set(material_table[['main_id', 'facility_group_id']].apply(tuple, axis=1))
#ids_biosphere = set(biosphere_table[['main_id', 'facility_group_id']].apply(tuple, axis=1))
#ids_land = set(land_table[['main_id', 'facility_group_id']].apply(tuple, axis=1))

In [26]:
# Facilities with at least technosphere and biosphere flows
#best_ids = ids_energy & ids_material & ids_biosphere
#best_ids

## Harmonize units for the same substance_id

In [27]:
unit_mapping = {
'7732-18-5' : 'm3',
'NA - M10' : 'tonnes',
'NA - M09' : 'tonnes',
'NA - M16' : 'tonnes',
'630-08-0' : 'tonnes',
'NA - NOx' : 'tonnes',
'NA - 08' : 'kg',
'NA - 10' : 'tonnes',
'NA - 02' : 'kg',
'NA - M08' : 'tonnes',
'NA - GHG' : 'tCO2eq',
'NA - 12': 'kg',
'NA - SOx': 'tonnes'
}

In [28]:
conversion_factors = {
    ('kg', 'tonnes'): 1/1000,
    ('kg', 't'): 1/1000,
    ('tonnes', 'kg'): 1000,
    ('t', 'kg'): 1000,
    ('tonnes', 't'): 1,
    ('t', 'tonnes'): 1,
    ('ML', 'm3'): 1000,
    ('m3', 'ML'): 1/1000,
    ('L', 'm3'): 1/1000,
    ('m3', 'L'): 1000,
    ('Mm3', 'm3'): 1000000,
    ('km3', 'm3'): 1000,
    ('ktCO2eq', 'tCO2eq'): 1000,
    ('tCO2eq', 'ktCO2eq'): 1/1000
}

In [29]:
def update_units_and_values(row):
    substance_id = row['substance_id']
    current_unit = row['unit']
    value = row['value']

    if substance_id in unit_mapping:
        target_unit = unit_mapping[substance_id]

        if current_unit != target_unit:
            conversion_key = (current_unit, target_unit)
            if conversion_key in conversion_factors:
                value = value * conversion_factors[conversion_key]
            # Si la conversion n'est pas définie, la valeur reste inchangée

        current_unit = target_unit  # Mettre à jour l'unité

    return pd.Series({'unit': current_unit, 'value': value})

In [30]:
env_table['value'] = pd.to_numeric(env_table['value'], errors='coerce')
mask = env_table['substance_id'].isin(unit_mapping.keys())
env_table.loc[mask, ['unit', 'value']] = env_table.loc[mask].apply(update_units_and_values, axis=1)

In [31]:
ghg_table['value'] = pd.to_numeric(ghg_table['value'], errors='coerce')
mask = ghg_table['substance_id'].isin(unit_mapping.keys())
ghg_table.loc[mask, ['unit', 'value']] = ghg_table.loc[mask].apply(update_units_and_values, axis=1)

## Aggregate data at facility-group level

In [32]:
biosphere_df = aggregate_biosphere_facility_groups(env_table, remove_individuals='True')

In [33]:
ghg_df = aggregate_biosphere_facility_groups(ghg_table, remove_individuals='False')

In [34]:
# To have the substance names
biosphere_df = biosphere_df.merge(substances_table[['substance_id', 'substance_name']], how='left',on='substance_id')

In [35]:
biosphere_df.to_excel(r'data/MetalliCan/pre_cleaned_data/biosphere_df.xlsx', index=False)

# Harmonization of technosphere units

In [36]:
# Separe energy and material
energy_df = technosphere_table[technosphere_table['flow_type'] == 'Energy']
material_df = technosphere_table[technosphere_table['flow_type'] == 'Material use']

## Energy flows

In [37]:
from utils.conversion_functions import standardize_energy_to_MJ

In [38]:
# Replace the unit 'kl' to 'm3' for Natural gas to avoid issues during conversion
energy_df.loc[(energy_df['subflow_type'] == 'Natural gas') & (energy_df['unit'] == 'kl'), 'unit'] = 'm3'

In [39]:
energy_df_sd = standardize_energy_to_MJ(energy_df)

In [40]:
energy_df_sd[energy_df_sd['value_MJ'].isna()]

Empty DataFrame
Columns: [technosphere_id, year, flow_type, subflow_type, unit, value, comment, main_id, facility_group_id, company_id, source_id, value_MJ, unit_source, assumption_note, unit_standard, needs_factor]
Index: []

In [41]:
# Check the rows where needs_factor is TRUE
energy_df_sd[energy_df_sd['value_MJ'].isna()]

Empty DataFrame
Columns: [technosphere_id, year, flow_type, subflow_type, unit, value, comment, main_id, facility_group_id, company_id, source_id, value_MJ, unit_source, assumption_note, unit_standard, needs_factor]
Index: []

In [42]:
energy_df_sd.to_excel(r'data/MetalliCan/pre_cleaned_data/energy_df.xlsx', index=False)

## Material flows

In [43]:
from utils.conversion_functions import standardize_materials_to_t

In [44]:
material_df_sd = standardize_materials_to_t(material_df)

In [45]:
# Check the rows where mass_t is NaN
material_df_sd[material_df_sd['mass_t'].isna()]

Empty DataFrame
Columns: [technosphere_id, year, flow_type, subflow_type, unit, value, comment, main_id, facility_group_id, company_id, source_id, mass_t, mass_source, mass_note, needs_density]
Index: []

In [46]:
material_df_sd.to_excel(r'data/MetalliCan/pre_cleaned_data/material_df.xlsx', index=False)

# Harmonization of land flows

In [47]:
# Step 1: Find main_id that have more than one unique source_id
multi_source_main_ids = land_table.groupby('main_id')['source_id'].nunique()
multi_source_main_ids = multi_source_main_ids[multi_source_main_ids > 1].index

# Step 2: Filter the dataframe
land_table = land_table[
    ~land_table['main_id'].isin(multi_source_main_ids) |
    (land_table['source_id'] == "https://www.nature.com/articles/s41597-025-05296-y")
]

In [48]:
# For each main_id, give the sum of area_km2 associated
land_table = land_table.groupby('main_id')['area_km2'].sum().reset_index()

In [49]:
land_table = land_table.merge(main_table[['main_id', 'facility_group_id', 'facility_name', 'facility_group_name', 'province', 'facility_type', 'mining_processing_type', 'commodities', 'operation_periods']], on='main_id', how='left')

In [50]:
land_table_mining = land_table[land_table['facility_type'] == 'mining']

In [51]:
# Add a column with area in m2 and
land_table_mining['area_m2'] = land_table_mining['area_km2'] * 1e6
land_table_mining.drop(columns=['area_km2'], inplace=True)

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_18344\2199434072.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  land_table_mining['area_m2'] = land_table_mining['area_km2'] * 1e6
C:\Users\mp_ma\AppData\Local\Temp\ipykernel_18344\2199434072.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  land_table_mining.drop(columns=['area_km2'], inplace=True)

In [52]:
land_table_mining

,main_id,facility_group_id,facility_name,facility_group_name,province,facility_type,mining_processing_type,commodities,operation_periods,area_m2
0,BC-MAIN-23155c25,NaN,Myra Falls,NaN,British Columbia,mining,Underground,"Zinc, copper, silver, gold, lead",1966–1985; 2002–2015; 2019–open,1.499690e+06
2,BC-MAIN-3f490561,NaN,Mount Polley,NaN,British Columbia,mining,"Open-pit, concentrator","Gold, copper, silver",NaN,7.967835e+06
3,BC-MAIN-4724f4ba,NaN,Elk,NaN,British Columbia,mining,Open-pit,Gold,NaN,4.167369e+05
4,BC-MAIN-599152a0,NaN,Copper Mountain,NaN,British Columbia,mining,"Open-pit, concentrator","Copper, gold, silver",1884–1958; 2011–open,1.323321e+07
5,BC-MAIN-6b4800fe,NaN,Gibraltar,NaN,British Columbia,mining,"Open-pit, concentrator","Copper, molybdenum, silver",1972–1998; 2004–open,2.252800e+07
...,...,...,...,...,...,...,...,...,...,...
110,SK-MAIN-91cf5448,NaN,Cigar Lake,NaN,Saskatchewan,mining,Underground,Uranium,2015–open,1.600590e+06
112,SK-MAIN-bb89158f,GRP-21eee27d,Key Lake,Key Lake + McArthur River,Saskatchewan,mining,Concentrator,Uranium,NaN,1.023565e+07
113,SK-MAIN-d3c471e8,GRP-21eee27d,McArthur River,Key Lake + McArthur River,Saskatchewan,mining,Underground,Uranium,NaN,1.973892e+06
114,YT-MAIN-44857446,NaN,Keno Hill Silver District,NaN,Yukon,mining,"Underground, concentrator","Silver, zinc, lead",NaN,5.293594e+06
115,YT-MAIN-752fbcae,NaN,Minto,NaN,Yukon,mining,"Open-pit, underground, concentrator","Copper, gold, silver",NaN,3.418676e+06

In [ ]:
from utils.data_manipulations import aggregate_land_facility_groups

In [55]:
land_table_mining = aggregate_land_facility_groups(land_table_mining)

In [56]:
land_table_mining

,main_id,facility_group_id,facility_name,facility_group_name,province,facility_type,mining_processing_type,commodities,operation_periods,area_m2
0,BC-MAIN-23155c25,NaN,Myra Falls,NaN,British Columbia,mining,Underground,"Zinc, copper, silver, gold, lead",1966–1985; 2002–2015; 2019–open,1.499690e+06
1,BC-MAIN-3f490561,NaN,Mount Polley,NaN,British Columbia,mining,"Open-pit, concentrator","Gold, copper, silver",NaN,7.967835e+06
2,BC-MAIN-4724f4ba,NaN,Elk,NaN,British Columbia,mining,Open-pit,Gold,NaN,4.167369e+05
3,BC-MAIN-599152a0,NaN,Copper Mountain,NaN,British Columbia,mining,"Open-pit, concentrator","Copper, gold, silver",1884–1958; 2011–open,1.323321e+07
4,BC-MAIN-6b4800fe,NaN,Gibraltar,NaN,British Columbia,mining,"Open-pit, concentrator","Copper, molybdenum, silver",1972–1998; 2004–open,2.252800e+07
...,...,...,...,...,...,...,...,...,...,...
83,None,GRP-25483238,,NaN,Quebec,mining,Open-pit,Ilmenite,1948–open,2.331099e+06
84,None,GRP-2a663492,,NaN,Newfoundland and Labrador,mining,Open-pit,Iron,<NA>,1.034080e+07
85,None,GRP-a13779f8,,NaN,Manitoba,mining,"Concentrator, Underground","Gold, zinc, copper, silver","2013–open, 1949–2000; 2021–open",3.104131e+06
86,None,GRP-dc07540b,,NaN,Ontario,mining,"Underground, Concentrator","Nickel, copper, platinum group metals, gold, s...",2014–open,2.941696e+07
87,None,GRP-de097f20,,NaN,Ontario,mining,"Underground, Concentrator","Nickel, copper, platinum group metals, gold, c...",1962–1991; 2007–2009; 2010–open,4.589124e+06

In [57]:
land_table_mining.to_excel(r'data/MetalliCan/pre_cleaned_data/land_table_mining.xlsx', index=False)

In [58]:
# Which ones do not have operation periods?
land_table_mining[land_table_mining['operation_periods'].isna()]

,main_id,facility_group_id,facility_name,facility_group_name,province,facility_type,mining_processing_type,commodities,operation_periods,area_m2
1,BC-MAIN-3f490561,NaN,Mount Polley,NaN,British Columbia,mining,"Open-pit, concentrator","Gold, copper, silver",NaN,7.967835e+06
2,BC-MAIN-4724f4ba,NaN,Elk,NaN,British Columbia,mining,Open-pit,Gold,NaN,4.167369e+05
7,BC-MAIN-bf503b6b,NaN,Highland Valley,NaN,British Columbia,mining,"Open-pit, concentrator","Copper, silver, molybdenum",NaN,6.392426e+07
9,MB-MAIN-0898e255,GRP-a13779f8,Stall Lake,Snow Lake,Manitoba,mining,Concentrator,"Gold, zinc",NaN,3.300033e+05
10,MB-MAIN-915d9faa,NaN,Tanco,NaN,Manitoba,mining,"Underground, concentrator, plant","Cesium, lithium",NaN,1.058100e+06
13,MB-MAIN-e0a6250e,NaN,Thompson (T-1 and T-3),NaN,Manitoba,mining,"Open-pit, underground, concentrator","Nickel, cobalt, copper, platinum group metals,...",NaN,7.481998e+06
15,NL-MAIN-842ba1b4,NaN,Nugget Pond,NaN,Newfoundland and Labrador,mining,Concentrator,Copper,NaN,1.632546e+05
16,NL-MAIN-b64bae7a,NaN,Scully,NaN,Newfoundland and Labrador,mining,"Open-pit, concentrator",Iron,NaN,1.057219e+07
17,NL-MAIN-c139de6d,NaN,Ming,NaN,Newfoundland and Labrador,mining,Underground,"Copper, gold, silver",NaN,1.510729e+06
18,NL-MAIN-dd723db4,NaN,Carol Lake,NaN,Newfoundland and Labrador,mining,"Open-pit, concentrator",Iron,NaN,2.610465e+07
19,NL-MAIN-e09881ff,GRP-2a663492,DSO (3 and 4),DSO,Newfoundland and Labrador,mining,Open-pit,Iron,NaN,1.034080e+07
20,NL-MAIN-f021107e,NaN,Point Rousse,NaN,Newfoundland and Labrador,mining,"Open-pit, concentrator",Gold,NaN,4.354811e+06
22,NT-MAIN-0ec39ce0,NaN,Diavik,NaN,Northwest Territories,mining,"Underground, plant",Diamonds,NaN,9.992992e+06
30,ON-MAIN-3b3e5365,NaN,Porcupine,NaN,Ontario,mining,Concentrator,Gold,NaN,3.512632e+06
31,ON-MAIN-48fe2205,GRP-dc07540b,Garson,Sudbury Operation,Ontario,mining,Underground,"Nickel, copper, platinum group metals, gold, s...",NaN,2.161806e+06
33,ON-MAIN-52224e1e,GRP-dc07540b,Creighton,Sudbury Operation,Ontario,mining,Underground,"Nickel, copper, platinum group metals, gold, s...",NaN,1.929968e+06
35,ON-MAIN-6e9b2449,GRP-dc07540b,Coleman,Sudbury Operation,Ontario,mining,Underground,"Nickel, copper, platinum group metals, gold, s...",NaN,1.108039e+05
37,ON-MAIN-7001a391,NaN,McCreedy West,NaN,Ontario,mining,Underground,"Copper, nickel, platinum group metals, gold, s...",NaN,9.891461e+05
40,ON-MAIN-8629a493,GRP-0d911886,Hollinger,Porcupine complex,Ontario,mining,Open-pit,Gold,NaN,1.141146e+06
41,ON-MAIN-8825d90d,NaN,Magino,NaN,Ontario,mining,"Open-pit, concentrator","Gold, silver",NaN,2.404687e+05
46,ON-MAIN-de2f9639,GRP-dc07540b,Clarabelle,Sudbury Operation,Ontario,mining,Concentrator,"Nickel, copper, platinum group metals, gold, s...",NaN,3.063893e+06
48,ON-MAIN-f080c409,GRP-dc07540b,Copper Cliff Complex,Sudbury Operation,Ontario,mining,Underground,"Nickel, copper, platinum group metals, gold, s...",NaN,2.159125e+07
51,ON-MAIN-fcb287a4,GRP-de097f20,Nickel Rim South,Integrated Nickel Operations,Ontario,mining,Underground,"Nickel, copper, cobalt, platinum group metals,...",NaN,1.788408e+06
55,QC-MAIN-089f3c60,NaN,Bloom Lake,NaN,Quebec,mining,Open-pit,Iron,NaN,1.570269e+07
57,QC-MAIN-33c09b8b,GRP-1402249f,Fire Lake,AMMC,Quebec,mining,Open-pit,Iron,NaN,3.714363e+06
65,QC-MAIN-dc1a16f9,NaN,North American Lithium,NaN,Quebec,mining,"Open-pit, underground",Lithium,NaN,2.689687e+06
69,QC-MAIN-f9e41c2a,NaN,Lamaque,NaN,Quebec,mining,"Underground, concentrator",Gold,NaN,1.190408e+07
70,SK-MAIN-29afbdb5,GRP-14bfbb82,Seabee,Seabee Gold Operation,Saskatchewan,mining,Concentrator,Gold,NaN,5.170040e+05
71,SK-MAIN-60ba74c4,NaN,McClean Lake,NaN,Saskatchewan,mining,Concentrator,Uranium,NaN,4.412887e+06
73,SK-MAIN-bb89158f,GRP-21eee27d,Key Lake,Key Lake + McArthur River,Saskatchewan,mining,Concentrator,Uranium,NaN,1.023565e+07
74,SK-MAIN-d3c471e8,GRP-21eee27d,McArthur River,Key Lake + McArthur River,Saskatchewan,mining,Underground,Uranium,NaN,1.973892e+06
75,YT-MAIN-44857446,NaN,Keno Hill Silver District,NaN,Yukon,mining,"Underground, concentrator","Silver, zinc, lead",NaN,5.293594e+06
76,YT-MAIN-752fbcae,NaN,Minto,NaN,Yukon,mining,"Open-pit, underground, concentrator","Copper, gold, silver",NaN,3.418676e+06
81,None,GRP-14bfbb82,,NaN,Saskatchewan,mining,Concentrator,Gold,<NA>,5.170040e+05
82,None,GRP-21eee27d,,NaN,Saskatchewan,mining,"Concentrator, Underground",Uranium,<NA>,1.220954e+07
84,None,GRP-2a663492,,NaN,Newfoundland and Labrador,mining,Open-pit,Iron,<NA>,1.034080e+07

# Sanity check for energy flows and GHG emissions

In [48]:
ef_df = pd.read_excel(r'data/Quality control/Emission_factors.xlsx', sheet_name='data')
ef_mapping_df = pd.read_excel(r'data/Quality control/Emission_factors.xlsx', sheet_name='MAPPING')

## Prepare clean GHG and energy dataframes

In [49]:
# Step 1: Find main_id that have more than one unique source_id
multi_source_main_ids = ghg_df.groupby('main_id')['source_id'].nunique()
multi_source_main_ids = multi_source_main_ids[multi_source_main_ids > 1].index

# Step 2: Filter the dataframe
ghg_df = ghg_df[
    ~ghg_df['main_id'].isin(multi_source_main_ids) |
    (ghg_df['source_id'] == "https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/greenhouse-gas-emissions/large-facilities.html")
]

In [50]:
energy_flow_to_check = ['Diesel', 'Gasoline', 'Propane','Natural gas', 'Aviation fuel','Electricity consumption|Generated on-site', 'Explosives', 'Oil', 'Light Fuel & Gasoline', 'Electricity consumption|Non-renewable electricity use', 'Non-renewable fuel use', 'Naphta', 'LPG', 'Petrol', 'Biodiesel', 'ANFO', 'Emulsion ANFO', 'Diesel|Mobile equipment', 'Gasoline|Mobile equipment', 'Diesel|Stationary equipment', 'LPG|Mobile equipment', 'LPG|Stationary equipment', 'Dynamite', 'Emulsions']
energy_df_check = energy_df_sd[energy_df_sd['subflow_type'].isin(energy_flow_to_check)]

In [51]:
ghg_df = add_site_id(ghg_df)
energy_df_check = add_site_id(energy_df_check)

In [52]:
ghg_df.to_csv(r'data/Quality control/ghg_flows.csv', index=False)
energy_df_check.to_csv(r'data/Quality control/energy_flows_to_check.csv', index=False)

## Check

In [53]:
from utils.constants import DEFAULT_LHV, DEFAULT_DENSITY
from utils.conversion_functions import convert_energy_to_fuel_units, compute_ghg_from_energy

In [70]:
energy_df_check["tCO2eq_estimated"] = energy_df_check.apply(
    lambda row: compute_ghg_from_energy(row, ef_mapping_df, ef_df, DEFAULT_LHV),
    axis=1
)

In [74]:
comparison = (
    energy_df_check.groupby("site_id")["tCO2eq_estimated"].sum()
    .to_frame("tCO2eq_estimated")
    .merge(
        ghg_df.groupby("site_id")["value"].sum(),
        left_index=True, right_index=True
    )
)

comparison["difference"] = comparison["tCO2eq_estimated"] - comparison["value"]
comparison["ratio"] = comparison["tCO2eq_estimated"] / comparison["value"]

In [79]:
comparison.to_excel(r'data/Quality control/ghg_comparison.xlsx', index=True)