In [57]:
import pandas as pd

In [58]:
# Cleaned data
energy_df = pd.read_excel(r'data\MetalliCan\pre_cleaned_data\energy_df.xlsx')
material_df = pd.read_excel(r'data\MetalliCan\pre_cleaned_data\material_df.xlsx')
biosphere_df = pd.read_excel(r'data\MetalliCan\pre_cleaned_data\biosphere_df.xlsx')
land_df = pd.read_excel(r'data\MetalliCan\pre_cleaned_data\land_df.xlsx')

In [59]:
# Prices and production data
price_df = pd.read_excel(r'data/Prices/Prices_data.xlsx', sheet_name='data')
production_df = pd.read_excel(r'data/MetalliCan/sites_for_lci.xlsx', sheet_name='prod_data')

In [60]:
production_df['archetypes'].unique()

array(['Co hydrometallurgical refinery', 'Zn refinery',
       'Porphyry sulfide, flotation-based', 'Free-miling',
       'Hybrid free-miling-refactory', 'Fe concentrator',
       'Ni hydrometallurgical refinery', 'Fe concentrator + pellet plant',
       'Direct Shipping Ore', 'Ni-Cu smelter',
       'Cu-Ni smelter and refinery', 'Magnetite concentrator',
       'Cu smelter', 'Nb smelter', 'Nb mine',
       'High-grade U acid-leach mills ',
       'High-grade polymetallic Pb-Zn-Ag'], dtype=object)

In [61]:
from utils.data_manipulations import build_activity_name, add_site_id

In [62]:
# Add site_id to dataframes
production_df = add_site_id(production_df)
energy_df = add_site_id(energy_df)
material_df = add_site_id(material_df)
biosphere_df = add_site_id(biosphere_df)
land_df = add_site_id(land_df)

In [63]:
# Add activitiy_name to production_df
production_df['activity_name'] = production_df.apply(lambda row: build_activity_name(row, production_df), axis=1)

In [64]:
energy_df = energy_df.merge(production_df[['site_id', 'activity_name', 'mining_processing_type', 'archetypes']], on='site_id', how='left')
material_df = material_df.merge(production_df[['site_id', 'activity_name', 'mining_processing_type', 'archetypes']], on='site_id', how='left')
biosphere_df = biosphere_df.merge(production_df[['site_id', 'activity_name', 'mining_processing_type', 'archetypes']], on='site_id', how='left')
land_df = land_df.merge(production_df[['site_id', 'activity_name','archetypes']], on='site_id', how='left')

In [65]:
# Replace column name mass_t to mass for normalization function
material_df = material_df.rename(columns={'mass_t': 'mass'})

In [35]:
biosphere_df

,env_id,year,compartment_name,substance_id,flow_direction,release_pathway,unit,value,comment,main_id,facility_group_id,company_id,source_id,substance_name,site_id,activity_name,mining_processing_type,archetypes
0,npri-1568-2023-1,2023,Air,NA - 16,Emission,Stack Emissions,tonnes,0.636000,NaN,ON-MAIN-1f126a43,<NA>,CMP-6265c407,https://www.canada.ca/en/environment-climate-c...,Ammonia (total),ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-miling
1,npri-1568-2023-2,2023,Air,NA - 02,Emission,Stack Emissions,kg,0.116000,NaN,ON-MAIN-1f126a43,<NA>,CMP-6265c407,https://www.canada.ca/en/environment-climate-c...,Arsenic (and its compounds),ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-miling
2,npri-1568-2023-3,2023,Air,630-08-0,Emission,Stack Emissions,tonnes,76.208000,NaN,ON-MAIN-1f126a43,<NA>,CMP-6265c407,https://www.canada.ca/en/environment-climate-c...,Carbon monoxide,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-miling
3,npri-1568-2023-4,2023,Air,NA - 04,Emission,Stack Emissions,tonnes,0.001050,NaN,ON-MAIN-1f126a43,<NA>,CMP-6265c407,https://www.canada.ca/en/environment-climate-c...,Chromium (and its compounds),ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-miling
4,npri-1568-2023-5,2023,Air,NA - 05,Emission,Stack Emissions,kg,0.180000,NaN,ON-MAIN-1f126a43,<NA>,CMP-6265c407,https://www.canada.ca/en/environment-climate-c...,Cobalt (and its compounds),ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-miling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5270,NaN,2023,Water,NA - 17,Emission,Waterbody,tonnes,0.000000,Aggregated value from multiple facilities,<NA>,GRP-de097f20,CMP-d5f1c66b,https://www.canada.ca/en/environment-climate-c...,Nitrate ion in solution at pH >= 6.0,GRP-de097f20,NaN,NaN,NaN
5271,NaN,2023,Water,NA - 37,Emission,Direct Discharge,kg,0.002100,Aggregated value from multiple facilities,<NA>,GRP-de097f20,CMP-d5f1c66b,https://www.canada.ca/en/environment-climate-c...,Thallium (and its compounds),GRP-de097f20,NaN,NaN,NaN
5272,NaN,2023,Water,NA - 37,Emission,Waterbody,kg,0.000000,Aggregated value from multiple facilities,<NA>,GRP-de097f20,CMP-d5f1c66b,https://www.canada.ca/en/environment-climate-c...,Thallium (and its compounds),GRP-de097f20,NaN,NaN,NaN
5273,NaN,2023,Water,NA - 40,Emission,Direct Discharge,tonnes,0.007037,Aggregated value from multiple facilities,<NA>,GRP-de097f20,CMP-d5f1c66b,https://www.canada.ca/en/environment-climate-c...,Vanadium (and its compounds),GRP-de097f20,NaN,NaN,NaN
5274,NaN,2023,Water,NA - 40,Emission,Waterbody,tonnes,0.000000,Aggregated value from multiple facilities,<NA>,GRP-de097f20,CMP-d5f1c66b,https://www.canada.ca/en/environment-climate-c...,Vanadium (and its compounds),GRP-de097f20,NaN,NaN,NaN

In [36]:
substance_ghg = ['124-38-9']
release_pathway = ['Stationary Fuel Combustion', 'On-site Transportation']
CO2_df = biosphere_df[
    biosphere_df['substance_id'].isin(substance_ghg) &
    biosphere_df['release_pathway'].isin(release_pathway)
]

# Keep only relevant columns

In [37]:
energy_col = ['site_id', 'activity_name', 'mining_processing_type', 'archetypes', 'flow_type', 'subflow_type', 'value_MJ']
material_col = ['site_id', 'activity_name', 'mining_processing_type', 'archetypes', 'flow_type', 'subflow_type', 'mass']
biosphere_col = ['site_id', 'activity_name', 'mining_processing_type', 'archetypes', 'compartment_name', 'substance_name', 'flow_direction', 'release_pathway', 'unit', 'value']
land_col = ['site_id', 'activity_name', 'mining_processing_type', 'archetypes', 'area_m2', 'operation_periods']

In [38]:
energy_df = energy_df[energy_col]
material_df = material_df[material_col]
biosphere_df = biosphere_df[biosphere_col]
CO2_df = CO2_df[biosphere_col]
land_df = land_df[land_col]

In [39]:
# Maybe need to differentiate unit and value in energy_df and material_df ?
energy_df['unit'] = 'MJ'
material_df['unit'] = 't'
land_df['unit'] = 'm2'
energy_df.rename(columns={'value_MJ': 'value'}, inplace=True) # maybe a problem for normalization function
material_df.rename(columns={'mass': 'value'}, inplace=True) # maybe a problem for normalization function
land_df.rename(columns={'area_m2': 'value'}, inplace=True) # maybe a problem for normalization function

In [40]:
# To know the % inferred vs 'primary'
energy_df['data_source'] = 'MetalliCan'
material_df['data_source'] = 'MetalliCan'
biosphere_df['data_source'] = 'MetalliCan'
CO2_df['data_source'] = 'MetalliCan'
land_df['data_source'] = 'MetalliCan'

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_20384\1843239807.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  biosphere_df['data_source'] = 'MetalliCan'

In [41]:
# To know the % inferred vs 'primary'
energy_df['value_formula'] = 'MetalliCan'
material_df['value_formula'] = 'MetalliCan'
biosphere_df['value_formula'] = 'MetalliCan'
CO2_df['value_formula'] = 'MetalliCan'
land_df['value_formula'] = 'MetalliCan'

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_20384\2105971740.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  biosphere_df['value_formula'] = 'MetalliCan'

# Data-gap filling

In [42]:
from core.data_gap_filling import *

In [43]:
# Initialize the InferenceEngine Class
engine = InferenceEngine(
    site_df=production_df,
    production_df=production_df,
    energy_df=energy_df,
    co2_df=CO2_df,
    land_df=land_df,
    material_df=material_df,
)

## Energy

In [44]:
site_id_to_fill_nrj = production_df[production_df['infer_energy_data'] == 'Yes']['site_id'].tolist()

In [45]:
ef = {
    "diesel": 2681,
    "natural_gas": 2354,
    "lpg": 2753
}

stationary_share_rules = {
    "Open-pit, concentrator": {"diesel": 0.7, "natural_gas": 0.2, "lpg": 0.1},
    "Underground, concentrator": {"diesel": 0.3, "natural_gas": 0.6, "lpg": 0.1},
}

default_shares = {"diesel": 0.3, "natural_gas": 0.6, "lpg": 0.1}

In [46]:
combined, inferred = engine.infer_energy_for_sites(
    site_ids=site_id_to_fill_nrj,
    ef_co2_per_unit=ef,
    stationary_share_rules=stationary_share_rules,
    default_shares=default_shares
)

In [47]:
inferred

,site_id,activity_name,mining_processing_type,archetypes,flow_type,subflow_type,value,unit,data_source,value_formula
0,AB-MAIN-d3a4aba9,Refining at The Cobalt Refinery Company Inc.,Refinery,Co hydrometallurgical refinery,Energy,Diesel|Transport,6.613078e+05,L,Inference from CO2 (transport diesel),(1772.9661 * 1e6) / 2681
1,AB-MAIN-d3a4aba9,Refining at The Cobalt Refinery Company Inc.,Refinery,Co hydrometallurgical refinery,Energy,Diesel|Stationary,2.361087e+07,L,Inference from CO2 (stationary diesel),(63300.737969999995 * 1e6) / 2681
2,AB-MAIN-d3a4aba9,Refining at The Cobalt Refinery Company Inc.,Refinery,Co hydrometallurgical refinery,Energy,Natural gas|Stationary,5.378143e+07,m3,Inference from CO2 (stationary natural gas),(126601.47593999999 * 1e6) / 2354
3,AB-MAIN-d3a4aba9,Refining at The Cobalt Refinery Company Inc.,Refinery,Co hydrometallurgical refinery,Energy,LPG|Stationary,7.664455e+06,L,Inference from CO2 (stationary LPG),(21100.24599 * 1e6) / 2753
4,BC-MAIN-3bb6b7cd,Refining at Trail,Refinery,Zn refinery,Energy,Diesel|Transport,8.863841e+05,L,Inference from CO2 (transport diesel),(2376.3958 * 1e6) / 2681
5,BC-MAIN-3bb6b7cd,Refining at Trail,Refinery,Zn refinery,Energy,Diesel|Stationary,3.291620e+07,L,Inference from CO2 (stationary diesel),(88248.34095 * 1e6) / 2681
6,BC-MAIN-3bb6b7cd,Refining at Trail,Refinery,Zn refinery,Energy,Natural gas|Stationary,7.497735e+07,m3,Inference from CO2 (stationary natural gas),(176496.6819 * 1e6) / 2354
7,BC-MAIN-3bb6b7cd,Refining at Trail,Refinery,Zn refinery,Energy,LPG|Stationary,1.068511e+07,L,Inference from CO2 (stationary LPG),(29416.113650000003 * 1e6) / 2753
8,BC-MAIN-3f490561,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Transport,1.738740e+07,L,Inference from CO2 (transport diesel),(46615.6208 * 1e6) / 2681
9,BC-MAIN-3f490561,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Stationary,2.394360e+05,L,Inference from CO2 (stationary diesel),(641.9279999999999 * 1e6) / 2681
10,BC-MAIN-3f490561,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Energy,Natural gas|Stationary,7.791334e+04,m3,Inference from CO2 (stationary natural gas),(183.40800000000002 * 1e6) / 2354
11,BC-MAIN-3f490561,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Energy,LPG|Stationary,3.331057e+04,L,Inference from CO2 (stationary LPG),(91.70400000000001 * 1e6) / 2753
12,BC-MAIN-bf503b6b,Open-pit mining and beneficiation at Highland ...,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Transport,6.003123e+07,L,Inference from CO2 (transport diesel),(160943.741 * 1e6) / 2681
13,BC-MAIN-bf503b6b,Open-pit mining and beneficiation at Highland ...,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Stationary,4.329585e+06,L,Inference from CO2 (stationary diesel),(11607.616369999998 * 1e6) / 2681
14,BC-MAIN-bf503b6b,Open-pit mining and beneficiation at Highland ...,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Energy,Natural gas|Stationary,1.408862e+06,m3,Inference from CO2 (stationary natural gas),(3316.46182 * 1e6) / 2354
15,BC-MAIN-bf503b6b,Open-pit mining and beneficiation at Highland ...,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Energy,LPG|Stationary,6.023360e+05,L,Inference from CO2 (stationary LPG),(1658.23091 * 1e6) / 2753
16,MB-MAIN-e0a6250e,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Transport,3.374935e+06,L,Inference from CO2 (transport diesel),(9048.2 * 1e6) / 2681
17,MB-MAIN-e0a6250e,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Stationary,1.041325e+06,L,Inference from CO2 (stationary diesel),(2791.7909999999997 * 1e6) / 2681
18,MB-MAIN-e0a6250e,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Natural gas|Stationary,2.371955e+06,m3,Inference from CO2 (stationary natural gas),(5583.581999999999 * 1e6) / 2354
19,MB-MAIN-e0a6250e,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,LPG|Stationary,3.380301e+05,L,Inference from CO2 (stationary LPG),(930.597 * 1e6) / 2753
20,NL-MAIN-2d8801d6,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Transport,1.465759e+07,L,Inference from CO2 (transport diesel),(39297.0 * 1e6) / 2681
21,NL-MAIN-2d8801d6,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Stationary,1.427982e+07,L,Inference from CO2 (stationary diesel),(38284.2 * 1e6) / 2681
22,NL-MAIN-2d8801d6,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Natural gas|Stationary,3.252693e+07,m3,Inference from CO2 (stationary natural gas),(76568.4 * 1e6) / 2354
23,NL-MAIN-2d8801d6,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,LPG|Stationary,4.635452e+06,L,Inference from CO2 (stationary LPG),(12761.400000000001 * 1e6) / 2753
24,NL-MAIN-d9036091,Refining at Long Harbour,Refinery,Ni hydrometallurgical refinery,Energy,Diesel|Transport,9.977881e+05,L,Inference from CO2 (transport diesel),(2675.07 * 1e6) / 2681
25,NL-MAIN-d9036091,Refining at Long Harbour,Refinery,Ni hydrometallurgical refinery,Energy,Diesel|Stationary,2.241697e+06,L,Inference from CO2 (stationary diesel),(6009.99 * 1e6) / 2681
26,NL-MAIN-d9036091,Refining at Long Harbour,Refinery,Ni hydrometallurgical refinery,Energy,Natural gas|Stationary,5.106194e+06,m3,Inference from CO2 (stationary natural gas),(12019.98 * 1e6) / 2354
27,NL-MAIN-d9036091,Refining at Long Harbour,Refinery,Ni hydrometallurgical refinery,Energy,LPG|Stationary,7.276898e+05,L,Inference from CO2 (stationary LPG),(2003.33 * 1e6) / 2753
28,NU-MAIN-5154702a,Open-pit mining at Mary River,Open-pit,Direct Shipping Ore,Energy,Diesel|Transport,2.419379e+07,L,Inference from CO2 (transport diesel),(64863.55484 * 1e6) / 2681
29,NU-MAIN-5154702a,Open-pit mining at Mary River,Open-pit,Direct Shipping Ore,Energy,Diesel|Stationary,2.649835e+06,L,Inference from CO2 (stationary diesel),(7104.207434999999 * 1e6) / 2681
30,NU-MAIN-5154702a,Open-pit mining at Mary River,Open-pit,Direct Shipping Ore,Energy,Natural gas|Stationary,6.035860e+06,m3,Inference from CO2 (stationary natural gas),(14208.414869999999 * 1e6) / 2354
31,NU-MAIN-5154702a,Open-pit mining at Mary River,Open-pit,Direct Shipping Ore,Energy,LPG|Stationary,8.601777e+05,L,Inference from CO2 (stationary LPG),(2368.069145 * 1e6) / 2753
32,QC-MAIN-089f3c60,Open-pit mining at Bloom Lake,Open-pit,Magnetite concentrator,Energy,Diesel|Transport,3.718453e+07,L,Inference from CO2 (transport diesel),(99691.72 * 1e6) / 2681
33,QC-MAIN-089f3c60,Open-pit mining at Bloom Lake,Open-pit,Magnetite concentrator,Energy,Diesel|Stationary,1.418597e+06,L,Inference from CO2 (stationary diesel),(3803.259 * 1e6) / 2681
34,QC-MAIN-089f3c60,Open-pit mining at Bloom Lake,Open-pit,Magnetite concentrator,Energy,Natural gas|Stationary,3.231316e+06,m3,Inference from CO2 (stationary natural gas),(7606.518 * 1e6) / 2354
35,QC-MAIN-089f3c60,Open-pit mining at Bloom Lake,Open-pit,Magnetite concentrator,Energy,LPG|Stationary,4.604987e+05,L,Inference from CO2 (stationary LPG),(1267.7530000000002 * 1e6) / 2753
36,QC-MAIN-5ce331b8,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Transport,1.225045e+07,L,Inference from CO2 (transport diesel),(32843.45 * 1e6) / 2681
37,QC-MAIN-5ce331b8,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Stationary,1.049707e+07,L,Inference from CO2 (stationary diesel),(28142.658 * 1e6) / 2681
38,QC-MAIN-5ce331b8,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,Natural gas|Stationary,2.391050e+07,m3,Inference from CO2 (stationary natural gas),(56285.316 * 1e6) / 2354
39,QC-MAIN-5ce331b8,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Energy,LPG|Stationary,3.407514e+06,L,Inference from CO2 (stationary LPG),(9380.886 * 1e6) / 2753
40,QC-MAIN-a555d9b9,Underground mining and beneficiation at Niobec,"Underground, concentrator",Nb mine,Energy,Diesel|Transport,1.989362e+06,L,Inference from CO2 (transport diesel),(5333.48 * 1e6) / 2681
41,QC-MAIN-a555d9b9,Underground mining and beneficiation at Niobec,"Underground, concentrator",Nb mine,Energy,Diesel|Stationary,7.191171e+05,L,Inference from CO2 (stationary diesel),(1927.953 * 1e6) / 2681
42,QC-MAIN-a555d9b9,Underground mining and beneficiation at Niobec,"Underground, concentrator",Nb mine,Energy,Natural gas|Stationary,1.638023e+06,m3,Inference from CO2 (stationary natural gas),(3855.906 * 1e6) / 2354
43,QC-MAIN-a555d9b9,Underground mining and beneficiation at Niobec,"Underground, concentrator",Nb mine,Energy,LPG|Stationary,2.334366e+05,L,Inference from CO2 (stationary LPG),(642.6510000000001 * 1e6) / 2753
44,QC-MAIN-a97821c0,Underground mining and beneficiation at Raglan,"Underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Transport,6.363417e+06,L,Inference from CO2 (transport diesel),(17060.32142 * 1e6) / 2681
45,QC-MAIN-a97821c0,Underground mining and beneficiation at Raglan,"Underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Stationary,1.544615e+07,L,Inference from CO2 (stationary diesel),(41411.13374999999 * 1e6) / 2681
46,QC-MAIN-a97821c0,Underground mining and beneficiation at Raglan,"Underground, concentrator","Porphyry sulfide, flotation-based",Energy,Natural gas|Stationary,3.518363e+07,m3,Inference from CO2 (stationary natural gas),(82822.26749999999 * 1e6) / 2354
47,QC-MAIN-a97821c0,Underground mining and beneficiation at Raglan,"Underground, concentrator","Porphyry sulfide, flotation-based",Energy,LPG|Stationary,5.014061e+06,L,Inference from CO2 (stationary LPG),(13803.71125 * 1e6) / 2753
48,SK-MAIN-60ba74c4,and beneficiation at McClean Lake,Concentrator,High-grade U acid-leach mills,Energy,Diesel|Transport,6.640070e+05,L,Inference from CO2 (transport diesel),(1780.2028 * 1e6) / 2681
49,SK-MAIN-60ba74c4,and beneficiation at McClean Lake,Concentrator,High-grade U acid-leach mills,Energy,Diesel|Stationary,2.138831e+06,L,Inference from CO2 (stationary diesel),(5734.206149999999 * 1e6) / 2681
50,SK-MAIN-60ba74c4,and beneficiation at McClean Lake,Concentrator,High-grade U acid-leach mills,Energy,Natural gas|Stationary,4.871883e+06,m3,Inference from CO2 (stationary natural gas),(11468.412299999998 * 1e6) / 2354
51,SK-MAIN-60ba74c4,and beneficiation at McClean Lake,Concentrator,High-grade U acid-leach mills,Energy,LPG|Stationary,6.942979e+05,L,Inference from CO2 (stationary LPG),(1911.40205 * 1e6) / 2753
52,SK-MAIN-91cf5448,Underground mining at Cigar Lake,Underground,High-grade U acid-leach mills,Energy,Diesel|Transport,2.525661e+06,L,Inference from CO2 (transport diesel),(6771.2984 * 1e6) / 2681
53,SK-MAIN-91cf5448,Underground mining at Cigar Lake,Underground,High-grade U acid-leach mills,Energy,Diesel|Stationary,1.424804e+06,L,Inference from CO2 (stationary diesel),(3819.8990099999996 * 1e6) / 2681
54,SK-MAIN-91cf5448,Underground mining at Cigar Lake,Underground,High-grade U acid-leach mills,Energy,Natural gas|Stationary,3.245454e+06,m3,Inference from CO2 (stationary natural gas),(7639.798019999999 * 1e6) / 2354
55,SK-MAIN-91cf5448,Underground mining at Cigar Lake,Underground,High-grade U acid-leach mills,Energy,LPG|Stationary,4.625135e+05,L,Inference from CO2 (stationary LPG),(1273.29967 * 1e6) / 2753

## Material

## Land

In [17]:
land_df

,site_id,activity_name,mining_processing_type,archetypes,value,operation_periods,unit,data_source
0,BC-MAIN-23155c25,NaN,Underground,NaN,1.499690e+06,1966–1985; 2002–2015; 2019–open,m2,MetalliCan
1,BC-MAIN-3ef4f421,NaN,NaN,NaN,1.396089e+06,NaN,m2,MetalliCan
2,BC-MAIN-3f490561,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",7.967835e+06,NaN,m2,MetalliCan
3,BC-MAIN-4724f4ba,Open-pit mining at Elk,Open-pit,Free-miling,4.167369e+05,NaN,m2,MetalliCan
4,BC-MAIN-599152a0,Open-pit mining and beneficiation at Copper Mo...,"Open-pit, concentrator","Porphyry sulfide, flotation-based",1.323321e+07,1884–1958; 2011–open,m2,MetalliCan
...,...,...,...,...,...,...,...,...
125,GRP-7a9ba115,NaN,Electric arc furnace,NaN,1.991940e+06,NaN,m2,MetalliCan
126,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Concentrator, Underground",Free-miling,3.104131e+06,"2013–open, 1949–2000; 2021–open",m2,MetalliCan
127,GRP-b48ec279,NaN,Smelter,NaN,6.630997e+06,NaN,m2,MetalliCan
128,GRP-dc07540b,NaN,"Underground, Smelter, refinery, plant, Concent...",NaN,3.338002e+07,2014–open,m2,MetalliCan
129,GRP-de097f20,NaN,"Underground, Smelter, plant, Concentrator",NaN,1.142796e+07,1962–1991; 2007–2009; 2010–open,m2,MetalliCan

In [48]:
site_id_to_fill_land = production_df[production_df['infer_land_data'] == 'Yes']['site_id'].tolist()

In [49]:
combined, inferred = engine.infer_land_for_sites(
    site_ids=site_id_to_fill_land,
    formula_open_pit="0.791 * ore_processed_t - 7.76e5",
    formula_underground="Uniform(5e5, 2e6)",
    formula_other="Uniform(1e4, 1e5)",
    overwrite=False
)

In [50]:
inferred

,site_id,activity_name,mining_processing_type,archetypes,value,operation_periods,unit,data_source,value_formula
0,AB-MAIN-d3a4aba9,Refining at The Cobalt Refinery Company Inc.,Refinery,Co hydrometallurgical refinery,NaN,None,m2,Inference (other facilities range),"Uniform(1e4, 1e5)"
1,BC-MAIN-3bb6b7cd,Refining at Trail,Refinery,Zn refinery,NaN,None,m2,Inference (other facilities range),"Uniform(1e4, 1e5)"
2,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-miling-refactory,NaN,None,m2,Inference (underground range),"Uniform(5e5, 2e6)"
3,NU-MAIN-5154702a,Open-pit mining at Mary River,Open-pit,Direct Shipping Ore,3.653600e+06,None,m2,Inference (open-pit model),(0.791 * 5600000.0) - 7.76e5
4,ON-MAIN-687b8c8d,Underground mining and beneficiation at Island,"Underground, concentrator",Free-miling,NaN,None,m2,Inference (underground range),"Uniform(5e5, 2e6)"
5,ON-MAIN-f4fc3276,Underground mining and beneficiation at Sugar ...,"Underground, concentrator",Free-miling,NaN,None,m2,Inference (underground range),"Uniform(5e5, 2e6)"
6,QC-MAIN-5ce331b8,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",8.014118e+04,None,m2,Inference (open-pit model),(0.791 * 1082352.94117647) - 7.76e5

In [20]:
inferred

,site_id,activity_name,mining_processing_type,archetypes,value,operation_periods,unit,data_source
0,AB-MAIN-d3a4aba9,Refining at The Cobalt Refinery Company Inc.,Refinery,Co hydrometallurgical refinery,NaN,None,m2,Inference (other facilities range)
1,BC-MAIN-3bb6b7cd,Refining at Trail,Refinery,Zn refinery,NaN,None,m2,Inference (other facilities range)
2,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-miling-refactory,NaN,None,m2,Inference (underground range)
3,NU-MAIN-5154702a,Open-pit mining at Mary River,Open-pit,Direct Shipping Ore,3.653600e+06,None,m2,Inference (open-pit model)
4,ON-MAIN-687b8c8d,Underground mining and beneficiation at Island,"Underground, concentrator",Free-miling,NaN,None,m2,Inference (underground range)
5,ON-MAIN-f4fc3276,Underground mining and beneficiation at Sugar ...,"Underground, concentrator",Free-miling,NaN,None,m2,Inference (underground range)
6,QC-MAIN-5ce331b8,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",8.014118e+04,None,m2,Inference (open-pit model)

In [22]:
inferred.columns

Index(['site_id', 'activity_name', 'mining_processing_type', 'archetypes',
       'value', 'operation_periods', 'unit', 'data_source'],
      dtype='object')

## Normalize flows

In [66]:
from core.normalization_allocation import normalize_flows

### Per ore processed

In [67]:
energy_ore = normalize_flows(energy_df, production_df, mode='ore', value_col='value_MJ')

In [68]:
material_ore = normalize_flows(material_df, production_df, mode='ore', value_col='mass')

In [69]:
biosphere_ore = normalize_flows(biosphere_df, production_df, mode='ore', value_col='value')

### Per concentrate stream

In [70]:
energy_conc_econ = normalize_flows(energy_df, production_df, price_df=price_df, mode='concentrate', allocation='economic', value_col='value_MJ')

In [71]:
material_conc_econ = normalize_flows(material_df, production_df, price_df=price_df,  mode='concentrate', allocation='economic', value_col='mass')

In [72]:
biosphere_conc_econ = normalize_flows(biosphere_df, production_df, price_df=price_df, mode='concentrate', allocation='economic', value_col='value')

### Per metal produced

In [73]:
energy_metal_econ = normalize_flows(energy_df, production_df, price_df=price_df, mode='metal', allocation='economic', value_col='value_MJ')

In [74]:
material_metal_econ = normalize_flows(material_df, production_df, price_df=price_df,  mode='metal', allocation='economic', value_col='mass')

In [75]:
biosphere_metal_econ = normalize_flows(biosphere_df, production_df, price_df=price_df, mode='metal', allocation='economic', value_col='value')

# Keeping only relevant columns

In [76]:
technosphere_col = ['activity_name', 'functional_unit', 'site_id', 'subflow_type', 'value_normalized']
biosphere_col = ['activity_name', 'functional_unit', 'site_id', 'substance_name', 'value_normalized', 'unit']

# Exports normalized dataframes

In [77]:
energy_ore.to_csv(r'data/MetalliCan/data_for_lci_initialization/ore/energy_df.csv', index=False)
material_ore.to_csv(r'data/MetalliCan/data_for_lci_initialization/ore/material_df.csv', index=False)
biosphere_ore.to_csv(r'data/MetalliCan/data_for_lci_initialization/ore/biosphere_df.csv', index=False)

In [78]:
energy_conc_econ.to_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/energy_df.csv', index=False)
material_conc_econ.to_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/material_df.csv', index=False)
biosphere_conc_econ.to_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/biosphere_df.csv', index=False)

In [79]:
energy_metal_econ.to_csv(r'data/MetalliCan/data_for_lci_initialization/metal/energy_df.csv', index=False)
material_metal_econ.to_csv(r'data/MetalliCan/data_for_lci_initialization/metal/material_df.csv', index=False)
biosphere_metal_econ.to_csv(r'data/MetalliCan/data_for_lci_initialization/metal/biosphere_df.csv', index=False)