In [150]:
import pandas as pd
import plotly.graph_objects as go

# Plot selected sites

In [151]:
production_df = pd.read_excel(r'data/MetalliCan/sites_for_lci.xlsx', sheet_name='prod_data')

In [152]:
#plot_sankey_hierarchy(production_df, columns_to_plot, html_output="data/MetalliCan/sites_for_lci_archetypes.html")

# Import cleaned MetalliCan data

In [153]:
from utils.data_manipulations import build_activity_name, add_site_id

In [154]:
# Pre-processed production table
production_df = pd.read_excel(r'data/MetalliCan/sites_for_lci.xlsx', sheet_name='prod_data')

In [155]:
# Add activitiy_name to production_df and site_id
production_df['activity_name'] = production_df.apply(lambda row: build_activity_name(row, production_df), axis=1)
production_df = add_site_id(production_df)

In [156]:
production_df

,main_id,facility_group_id,facility_name,facility_group_name,province,facility_type,mining_processing_type,archetypes,biosphere_data?,technosphere_data?,...,Zn_conc,Pb_conc,Fe_conc,Pt_conc,Pd_conc,U_conc,Nb_conc,Au_conc,activity_name,site_id
0,AB-MAIN-d3a4aba9,<NA>,The Cobalt Refinery Company Inc.,NaN,Alberta,manufacturing,Refinery,Co hydrometallurgical refinery,NPRI+GHG,(NRJ could be back calculated with GHG),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,refining at The Cobalt Refinery Company Inc.,AB-MAIN-d3a4aba9
1,BC-MAIN-3bb6b7cd,<NA>,Trail,NaN,British Columbia,manufacturing,Refinery,Zn refinery,NPRI+GHG+Water,(NRJ could be back calculated with GHG),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,refining at Trail,BC-MAIN-3bb6b7cd
2,BC-MAIN-3f490561,<NA>,Mount Polley,NaN,British Columbia,mining,"Open-pit, concentrator","Porphyry sulfide, flotation-based",NPRI+GHG+Land,(NRJ could be back calculated with GHG),...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,Open-pit mining and beneficiation at Mount Polley,BC-MAIN-3f490561
3,BC-MAIN-4724f4ba,<NA>,Elk,NaN,British Columbia,mining,Open-pit,Free-miling,Land,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.124287,Open-pit mining at Elk,BC-MAIN-4724f4ba
4,BC-MAIN-599152a0,<NA>,Copper Mountain,NaN,British Columbia,mining,"Open-pit, concentrator","Porphyry sulfide, flotation-based",NPRI+GHG+Land,Energy (but sanity issue),...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,Open-pit mining and beneficiation at Copper Mo...,BC-MAIN-599152a0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,<NA>,GRP-0a2c0d69,NaN,Meadowbank complex,Nunavut,mining,"Open-pit, underground",Free-miling,NPRI+GHG+Land,Energy,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,17.667601,Open-pit and underground mining at Meadowbank ...,GRP-0a2c0d69
62,<NA>,GRP-0d911886,NaN,Porcupine complex,Ontario,mining,"Open-pit, underground",Free-miling,NPRI+GHG+Land,Energy and materials,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,8.251949,Open-pit and underground mining at Porcupine c...,GRP-0d911886
63,<NA>,GRP-147b3123,NaN,Timmins Operation,Ontario,mining,"Underground, concentrator",Free-miling,NPRI+GHG+Land,Energy (but sanity issue),...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,4.218015,Underground mining and beneficiation at Timmin...,GRP-147b3123
64,<NA>,GRP-14bfbb82,NaN,Seabee Gold Operation,Saskatchewan,mining,"Underground, concentrator",Free-miling,NPRI+GHG+Land,Energy (but sanity issue),...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,1.230080,Underground mining and beneficiation at Seabee...,GRP-14bfbb82
65,<NA>,GRP-a13779f8,NaN,Snow Lake,Manitoba,mining,"Underground, concentrator",Free-miling,NPRI+Land,Energy (but sanity issue),...,69284.0,0.0,0.0,NaN,NaN,NaN,0.0,32.978787,Underground mining and beneficiation at Snow Lake,GRP-a13779f8

In [157]:
# Normalized MetalliCan tables per ore processed
energy_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/energy_df.csv')
material_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/material_df.csv')
biosphere_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/biosphere_df.csv')

In [158]:
# Normalized MetalliCan tables per ore processed
energy_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/energy_df.csv')
material_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/material_df.csv')
biosphere_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/biosphere_df.csv')

In [159]:
energy_stream_df

,technosphere_id,year,flow_type,subflow_type,unit,value,comment,main_id,facility_group_id,company_id,...,activity_name,mining_processing_type,archetypes,concentrate,mass_conc,allocation_factor,facility_type,value_normalized,functional_unit,normalization_key
0,TECH-857b7b89-2023.0-1.0,2023.0,Energy,Acetylene,GJ,18.475651,NaN,BC-MAIN-857b7b89,NaN,CMP-4a434d72,...,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-miling-refactory,Au,0.920410,1.0,mining,2.007329e+04,Doré,concentrate_economic
1,TECH-857b7b89-2023.0-2.0,2023.0,Energy,Aviation fuel,GJ,72676.110790,NaN,BC-MAIN-857b7b89,NaN,CMP-4a434d72,...,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-miling-refactory,Au,0.920410,1.0,mining,7.896061e+07,Doré,concentrate_economic
2,TECH-857b7b89-2023.0-3.0,2023.0,Energy,Diesel,GJ,287042.447232,NaN,BC-MAIN-857b7b89,NaN,CMP-4a434d72,...,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-miling-refactory,Au,0.920410,1.0,mining,3.118638e+08,Doré,concentrate_economic
3,TECH-857b7b89-2023.0-4.0,2023.0,Energy,Electricity consumption|Generated on-site,GJ,86225.117396,NaN,BC-MAIN-857b7b89,NaN,CMP-4a434d72,...,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-miling-refactory,Au,0.920410,1.0,mining,9.368124e+07,Doré,concentrate_economic
4,TECH-857b7b89-2023.0-5.0,2023.0,Energy,Electricity consumption|Grid electricity,GJ,569009.584800,NaN,BC-MAIN-857b7b89,NaN,CMP-4a434d72,...,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-miling-refactory,Au,0.920410,1.0,mining,6.182134e+08,Doré,concentrate_economic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,TECH-7607a50e-2023.0-2.0,2023.0,Energy,Electricity consumption|Generated on-site,GJ,475.000000,NaN,ON-MAIN-7607a50e,NaN,CMP-3a4ccc7f,...,Underground mining and beneficiation at Young-...,"Underground, concentrator",Free-miling,Au,5.874753,1.0,mining,8.085446e+04,Doré,concentrate_economic
193,TECH-7607a50e-2023.0-3.0,2023.0,Energy,Electricity consumption|Grid electricity,GJ,960748.000000,NaN,ON-MAIN-7607a50e,NaN,CMP-3a4ccc7f,...,Underground mining and beneficiation at Young-...,"Underground, concentrator",Free-miling,Au,5.874753,1.0,mining,1.635385e+08,Doré,concentrate_economic
194,TECH-7607a50e-2023.0-4.0,2023.0,Energy,Gasoline,GJ,2124.000000,NaN,ON-MAIN-7607a50e,NaN,CMP-3a4ccc7f,...,Underground mining and beneficiation at Young-...,"Underground, concentrator",Free-miling,Au,5.874753,1.0,mining,3.615471e+05,Doré,concentrate_economic
195,TECH-7607a50e-2023.0-5.0,2023.0,Energy,Naphta,GJ,6344.000000,NaN,ON-MAIN-7607a50e,NaN,CMP-3a4ccc7f,...,Underground mining and beneficiation at Young-...,"Underground, concentrator",Free-miling,Au,5.874753,1.0,mining,1.079875e+06,Doré,concentrate_economic
196,TECH-7607a50e-2023.0-6.0,2023.0,Energy,Natural gas,GJ,221612.000000,NaN,ON-MAIN-7607a50e,NaN,CMP-3a4ccc7f,...,Underground mining and beneficiation at Young-...,"Underground, concentrator",Free-miling,Au,5.874753,1.0,mining,3.772278e+07,Doré,concentrate_economic

In [160]:
# Normalized MetalliCan tables per metal, economic allocation
# energy_econ_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/economic_allocation/energy_df.csv')
# material_econ_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/economic_allocation/material_df.csv')
# biosphere_econ_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/economic_allocation/biosphere_df.csv')

In [161]:
# Removing rows with value_normalized is NaN in the biosphere dfs
biosphere_ore_df = biosphere_ore_df[~biosphere_ore_df['value_normalized'].isna()]
biosphere_stream_df['value_normalized'] = biosphere_stream_df['value_normalized'] / 1e6

In [162]:
# For all the dfs, multiply the value_normalized to 10e6 to have values per kg
energy_ore_df['value_normalized'] = energy_ore_df['value_normalized'] / 1e6
material_ore_df['value_normalized'] = material_ore_df['value_normalized'] / 1e6
biosphere_ore_df['value_normalized'] = biosphere_ore_df['value_normalized'] / 1e6
energy_stream_df['value_normalized'] = energy_stream_df['value_normalized'] / 1e6
material_stream_df['value_normalized'] = material_stream_df['value_normalized'] / 1e6
biosphere_stream_df['value_normalized'] = biosphere_stream_df['value_normalized'] / 1e6

# Keeping only relevant columns

In [163]:
technosphere_col = ['activity_name', 'functional_unit', 'site_id', 'subflow_type', 'value_normalized']
biosphere_col = ['activity_name', 'functional_unit', 'site_id', 'substance_name', 'value_normalized', 'unit']

In [164]:
energy_ore_df = energy_ore_df[technosphere_col]
material_ore_df = material_ore_df[technosphere_col]
biosphere_ore_df = biosphere_ore_df[biosphere_col]
energy_stream_df = energy_stream_df[technosphere_col]
material_stream_df = material_stream_df[technosphere_col]
biosphere_stream_df = biosphere_stream_df[biosphere_col]

In [165]:
# Add units to technosphere dfs
energy_ore_df['unit'] = 'MJ'
material_ore_df['unit'] = 't'
energy_stream_df['unit'] = 'MJ'
material_stream_df['unit'] = 't'

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_6028\1661232123.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  energy_stream_df['unit'] = 'MJ'

In [166]:
# Put energy_df and material_df together
technosphere_ore_df = pd.concat([energy_ore_df, material_ore_df], ignore_index=True)
technosphere_stream_df = pd.concat([energy_stream_df, material_stream_df], ignore_index=True)

In [167]:
# Add the province from the main_df to specify electricity location later
technosphere_ore_df = technosphere_ore_df.merge(production_df[['site_id', 'province']], on=['site_id'], how='left')
technosphere_stream_df = technosphere_stream_df.merge(production_df[['site_id', 'province']], on=['site_id'], how='left')
biosphere_ore_df = biosphere_ore_df.merge(production_df[['site_id', 'province']], on=['site_id'], how='left')
biosphere_stream_df = biosphere_stream_df.merge(production_df[['site_id', 'province']], on=['site_id'], how='left')

# Map MetalliCan flows to EI and RI flows

In [168]:
from utils.conversion_functions import map_technosphere_to_ecoinvent, map_biosphere_to_ecoinvent
from utils.constants import CA_provinces

## Technosphere flows

In [169]:
mapping_technosphere = pd.read_excel(r'data/Mappings/MAPPINGS_RI.xlsx', sheet_name='technosphere')

In [170]:
technosphere_ore_df

,activity_name,functional_unit,site_id,subflow_type,value_normalized,unit,province
0,Underground mining and beneficiation at Brucejack,Ore processed,BC-MAIN-857b7b89,Acetylene,1.112991e-07,MJ,British Columbia
1,Underground mining and beneficiation at Brucejack,Ore processed,BC-MAIN-857b7b89,Aviation fuel,4.378079e-04,MJ,British Columbia
2,Underground mining and beneficiation at Brucejack,Ore processed,BC-MAIN-857b7b89,Diesel,1.729171e-03,MJ,British Columbia
3,Underground mining and beneficiation at Brucejack,Ore processed,BC-MAIN-857b7b89,Electricity consumption|Generated on-site,5.194284e-04,MJ,British Columbia
4,Underground mining and beneficiation at Brucejack,Ore processed,BC-MAIN-857b7b89,Electricity consumption|Grid electricity,3.427769e-03,MJ,British Columbia
...,...,...,...,...,...,...,...
228,Underground mining and beneficiation at Westwo...,Ore processed,QC-MAIN-02884fb5,Motor/drill oil,1.827853e-11,t,Quebec
229,Underground mining and beneficiation at Westwo...,Ore processed,QC-MAIN-02884fb5,Sulfur dioxide,5.212766e-10,t,Quebec
230,Underground mining and beneficiation at Westwo...,Ore processed,QC-MAIN-02884fb5,Transmission oil,7.833656e-12,t,Quebec
231,Underground mining and beneficiation at Young-...,Ore processed,ON-MAIN-7607a50e,Total blasting agents used e.g. ANFO,9.032167e-10,t,Ontario
232,Underground mining and beneficiation at Young-...,Ore processed,ON-MAIN-7607a50e,Total sodium cyanide used,6.795233e-10,t,Ontario

In [184]:
# Apply the function
mapped_technosphere_ore_df = map_technosphere_to_ecoinvent(technosphere_ore_df, mapping_technosphere, CA_provinces)
mapped_technosphere_stream_df = map_technosphere_to_ecoinvent(technosphere_stream_df, mapping_technosphere, CA_provinces)

⚠️ Les flux suivants n'ont pas trouvé de correspondance dans Ecoinvent:
 - Energy use
 - Other
 - Surface/underground emulsion & ANFO
⚠️ Pas de conversion définie pour MJ → kilogram (flux: Ammonium nitrate)
⚠️ Pas de conversion définie pour MJ → kilogram (flux: Dynamite)
⚠️ Les flux suivants n'ont pas trouvé de correspondance dans Ecoinvent:
 - Other
 - Surface/underground emulsion & ANFO
⚠️ Pas de conversion définie pour MJ → kilogram (flux: Ammonium nitrate)
⚠️ Pas de conversion définie pour MJ → kilogram (flux: Dynamite)

In [185]:
# Drop rows where ecoinvent_flow_name is "No mapping" and Amount is NaN for now
mapped_technosphere_ore_df = mapped_technosphere_ore_df[(mapped_technosphere_ore_df["Activity"] != "No mapping") & (~mapped_technosphere_ore_df["Amount"].isna())]
mapped_technosphere_stream_df = mapped_technosphere_stream_df[(mapped_technosphere_stream_df["Activity"] != "No mapping") & (~mapped_technosphere_stream_df["Amount"].isna())]

In [186]:
technosphere_col_for_lci = ['site_id', 'activity_name', 'functional_unit', 'Amount', 'Activity', 'Product', 'Unit', 'Location', 'Database']

In [187]:
mapped_technosphere_ore_df = mapped_technosphere_ore_df[technosphere_col_for_lci]
mapped_technosphere_stream_df = mapped_technosphere_stream_df[technosphere_col_for_lci]

## Biosphere flows mapping

In [188]:
mapping_biosphere = pd.read_excel(r'data/Mappings/MAPPINGS_RI.xlsx', sheet_name='biosphere')

In [189]:
mapped_biosphere_ore_df = map_biosphere_to_ecoinvent(biosphere_ore_df, mapping_biosphere, CA_provinces)
mapped_biosphere_stream_df = map_biosphere_to_ecoinvent(biosphere_stream_df, mapping_biosphere, CA_provinces)

Index(['activity_name', 'functional_unit', 'site_id', 'substance_name',
       'value_normalized', 'unit', 'province', 'Type', 'substance_id',
       'compartment_name', 'release_pathway', 'flow_direction',
       'MetalliCan_unit', 'DB_to_map', 'Flow name', 'Compartments', 'Unit',
       'Comment', 'Alternatives'],
      dtype='object')
⚠️ 6 biosphere flows could not be mapped to Ecoinvent:
   - 1-Nitropyrene
   - Quinoline
   - Ethylene glycol
   - nan
   - N2O
   - PFCs
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for kg → nan (flow: 1-Nitropyrene)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for kg → nan (flow: Quinoline)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for g teq → kilogram (flow: Dioxins and furans - total)
⚠️ No conversion defined for tonnes → nan (flow: Ethylene glycol)
⚠️ No conversion defined for tonnes → nan (flow: Ethylene glycol)
⚠️ No conversion defined for tonnes → nan (flow: Ethylene glycol)
⚠️ No conversion defined for tonnes → nan (flow: Ethylene glycol)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tco2eq → nan (flow: PFCs)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for ha → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: N2O)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)
⚠️ No conversion defined for tonnes → nan (flow: nan)

In [190]:
# Drop rows where ecoinvent_flow_name is "No mapping" and Amount is NaN for now
mapped_biosphere_ore_df = mapped_biosphere_ore_df[(mapped_biosphere_ore_df["Flow Name"] != "No mapping") & (~mapped_biosphere_ore_df["Amount"].isna())]
mapped_biosphere_stream_df = mapped_biosphere_stream_df[(mapped_biosphere_stream_df["Flow Name"] != "No mapping") & (~mapped_biosphere_stream_df["Amount"].isna())]

In [191]:
biosphere_col_for_lci = ['site_id', 'activity_name', 'functional_unit', 'Amount', 'Unit', 'Flow Name', 'Compartments', 'Database']

In [192]:
mapped_biosphere_ore_df = mapped_biosphere_ore_df[biosphere_col_for_lci]
mapped_biosphere_stream_df = mapped_biosphere_stream_df[biosphere_col_for_lci]

In [193]:
#mapped_biosphere_ore_df.to_csv(r'data/MetalliCan/data_for_lci_initialization/biosphere_ore_df.csv', index=False)
#mapped_biosphere_stream_df.to_csv(r'data/MetalliCan/data_for_lci_initialization/biosphere_stream_df.csv', index=False)

In [194]:
#mapped_technosphere_ore_df.to_csv(r'data/MetalliCan/data_for_lci_initialization/technosphere_ore_df.csv', index=False)
#mapped_technosphere_stream_df.to_csv(r'data/MetalliCan/data_for_lci_initialization/technosphere_stream_df.csv', index=False)

In [195]:
# Add province and commodities from NRCan to production table
mapped_biosphere_ore_df = mapped_biosphere_ore_df.merge(production_df[['site_id', 'province', 'commodities']], on=['site_id'], how='left')
mapped_biosphere_stream_df = mapped_biosphere_stream_df.merge(production_df[['site_id', 'province', 'commodities']], on=['site_id'], how='left')

In [196]:
mapped_technosphere_stream_df

,site_id,activity_name,functional_unit,Amount,Activity,Product,Unit,Location,Database
0,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,0.000418,consumption market for acetylene,acetylene,kilogram,CA,Regioinvent
1,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,1.832033,consumption market for kerosene,kerosene,kilogram,CA,Regioinvent
2,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,7.252646,consumption market for diesel,diesel,kilogram,CA,Regioinvent
3,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,2.178633,consumption market for diesel,diesel,kilogram,CA,Regioinvent
4,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,171.726075,"market for electricity, medium voltage","electricity, medium voltage",kilowatt hour,CA-BC,ecoinvent-3.10-cutoff regionalized
...,...,...,...,...,...,...,...,...,...
282,QC-MAIN-02884fb5,Underground mining and beneficiation at Westwo...,Doré,0.130883,"consumption market for sulfur dioxide, liquid","sulfur dioxide, liquid",kilogram,CA,Regioinvent
283,QC-MAIN-02884fb5,Underground mining and beneficiation at Westwo...,Doré,0.001967,consumption market for lubricating oil,lubricating oil,kilogram,CA,Regioinvent
284,ON-MAIN-7607a50e,Underground mining and beneficiation at Young-...,Doré,0.442487,"consumption market for explosive, tovex","explosive, tovex",kilogram,CA,Regioinvent
285,ON-MAIN-7607a50e,Underground mining and beneficiation at Young-...,Doré,0.442487,"consumption market for explosive, tovex","explosive, tovex",kilogram,CA,Regioinvent
286,ON-MAIN-7607a50e,Underground mining and beneficiation at Young-...,Doré,0.332899,consumption market for sodium cyanide,sodium cyanide,kilogram,CA,Regioinvent

In [197]:
mapped_biosphere_stream_df

,site_id,activity_name,functional_unit,Amount,Unit,Flow Name,Compartments,Database,province,commodities
0,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,8.768417e-11,kilogram,"Ammonia, CA-ON","('air', 'low population density long term')",biosphere3_spatialized_flows,Ontario,"Gold, silver"
1,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,8.768417e-11,kilogram,"Ammonia, CA-ON","('air', 'low population density long term')",biosphere3_spatialized_flows,Ontario,"Gold, silver"
2,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,8.768417e-11,kilogram,"Ammonia, CA-ON","('air', 'low population density long term')",biosphere3_spatialized_flows,Ontario,"Gold, silver"
3,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,8.768417e-11,kilogram,Ammonia,"('soil', 'industrial')",biosphere3,Ontario,"Gold, silver"
4,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,8.768417e-11,kilogram,Ammonium,"('water',)",biosphere3,Ontario,"Gold, silver"
...,...,...,...,...,...,...,...,...,...,...
11219,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Zn concentrate,0.000000e+00,kilogram,Nitrate,"('water',)",biosphere3,Manitoba,"Gold, zinc, copper, silver"
11220,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Zn concentrate,0.000000e+00,kilogram,Nitrate,"('water',)",biosphere3,Manitoba,"Gold, zinc, copper, silver"
11221,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Doré,0.000000e+00,kilogram,Nitrate,"('air',)",biosphere3,Manitoba,"Gold, zinc, copper, silver"
11222,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Doré,0.000000e+00,kilogram,Nitrate,"('water',)",biosphere3,Manitoba,"Gold, zinc, copper, silver"
11223,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Doré,0.000000e+00,kilogram,Nitrate,"('water',)",biosphere3,Manitoba,"Gold, zinc, copper, silver"

# LCI creation

In [205]:
from core.lci_database_builder import LCIDatabaseBuilder

## Ore processed basis

In [206]:
# Step 1 — initialize the builder
builder_op = LCIDatabaseBuilder(db_name='metallican_lci', project_name='metallican')

📂 Active Brightway project: metallican
🆕 Database 'metallican_lci' created.

In [207]:
# Step 2 — create the activity shells from the main dataframe
builder_op.build_lci_entries(df=mapped_biosphere_ore_df)
print(len(builder_op.lcis))

✅ Created 52 base LCI activities with production exchanges.
52

In [208]:
# Step 3a — Populate with the technosphere exchanges
builder_op.populate_technosphere_exchanges(technosphere_df=mapped_technosphere_ore_df)

⚙️ Populating technosphere exchanges

KeyboardInterrupt:

In [37]:
# Step 3b — Populate with the biosphere exchanges
builder_op.populate_biosphere_exchanges(biosphere_df=mapped_biosphere_ore_df)

🌱 Populating biosphere exchanges
   ✅ Cached 110559 biosphere flows from biosphere3_spatialized_flows
   ✅ Cached 4362 biosphere flows from biosphere3
✅ Added 7889 biosphere exchanges.

In [38]:
# Step 4 - Consolidate duplicate flows
builder_op.consolidate_exchanges()

🧮 Consolidation: 8168 → 849 exchanges (summed duplicates).

In [39]:
builder_op.write_to_database()

🧱 Writing 33 activities to database 'metallican_lci'...
✅ Database 'metallican_lci' processed successfully with 33 activities.

## Usable ore or metal basis

In [209]:
# Step 1 — initialize the builder
builder_uo = LCIDatabaseBuilder(db_name='metallican_lci', project_name='metallican')

📂 Active Brightway project: metallican
✅ Using existing database 'metallican_lci'.

In [210]:
# Step 2 — create the activity shells from the main dataframe
builder_uo.build_lci_entries(df=mapped_biosphere_stream_df)
print(len(builder_uo.lcis))

✅ Created 50 base LCI activities with production exchanges.
50

In [211]:
# Step 3a — Populate with the technosphere exchanges
builder_uo.populate_technosphere_exchanges(technosphere_df=mapped_technosphere_stream_df)

⚙️ Populating technosphere exchanges
   ✅ Cached 218246 activities from Regioinvent
   ✅ Cached 20769 activities from ecoinvent-3.10-cutoff regionalized
✅ Added 283 technosphere exchanges.

In [212]:
# Step 3b — Populate with the biosphere exchanges
builder_uo.populate_biosphere_exchanges(biosphere_df=mapped_biosphere_stream_df)

🌱 Populating biosphere exchanges
   ✅ Cached 110559 biosphere flows from biosphere3_spatialized_flows
   ✅ Cached 4362 biosphere flows from biosphere3
✅ Added 11224 biosphere exchanges.

In [213]:
# Step 4 - Consolidate duplicate flows
builder_uo.consolidate_exchanges()

🧮 Consolidation: 11557 → 1150 exchanges (summed duplicates).

In [214]:
builder_uo.write_to_database()

🧱 Writing 50 activities to database 'metallican_lci'...
✅ Database 'metallican_lci' processed successfully with 50 activities.