In [1]:
import pandas as pd
import plotly.graph_objects as go

# Plot selected sites

In [2]:
production_df = pd.read_excel(r'data/MetalliCan/sites_for_lci.xlsx', sheet_name='prod_data')

In [3]:
#plot_sankey_hierarchy(production_df, columns_to_plot, html_output="data/MetalliCan/sites_for_lci_archetypes.html")

# Import cleaned MetalliCan data

In [4]:
from utils.data_manipulations import build_activity_name, add_site_id

In [5]:
# Pre-processed production table
production_df = pd.read_excel(r'data/MetalliCan/sites_for_lci.xlsx', sheet_name='prod_data')

In [6]:
# Add activitiy_name to production_df and site_id
production_df['activity_name'] = production_df.apply(lambda row: build_activity_name(row, production_df), axis=1)
production_df = add_site_id(production_df)

In [7]:
production_df

,main_id,facility_group_id,facility_name,facility_group_name,province,facility_type,mining_processing_type,npv,archetypes,archetypes_detailed,...,Zn_conc,Pb_conc,Fe_conc,Pt_conc,Pd_conc,U_conc,Nb_conc,Au_conc,activity_name,site_id
0,QC-MAIN-089f3c60,<NA>,Bloom Lake,NaN,Quebec,mining,Open-pit,NaN,Magnetite concentrator,Only mining,...,0.0,0.000000,NaN,NaN,NaN,NaN,0.0,0.000000,Open-pit mining at Bloom Lake,QC-MAIN-089f3c60
1,BC-MAIN-857b7b89,<NA>,Brucejack,NaN,British Columbia,mining,"Underground, concentrator",Low and High Shrub Tundra,Au–Ag free-milling,Might contain refractory ore? Big GHG outlier,...,0.0,0.000000,NaN,NaN,NaN,NaN,0.0,0.920410,Underground mining and beneficiation at Brucejack,BC-MAIN-857b7b89
2,QC-MAIN-de3d8b7b,<NA>,Canadian Electrolytic Zinc Limited (CEZinc),NaN,Quebec,manufacturing,Refinery,NaN,Zn refinery,NaN,...,NaN,407666.666667,NaN,NaN,NaN,NaN,NaN,0.000000,Refining at Canadian Electrolytic Zinc Limited...,QC-MAIN-de3d8b7b
3,QC-MAIN-e7e6a960,<NA>,Canadian Malartic,NaN,Quebec,mining,"Open-pit, concentrator",Cool Mixed Forest,Au–Ag free-milling,Might contain refractory ore?,...,0.0,0.000000,NaN,NaN,NaN,NaN,0.0,29.039085,Open-pit mining and beneficiation at Canadian ...,QC-MAIN-e7e6a960
4,NL-MAIN-dd723db4,<NA>,Carol Lake,NaN,Newfoundland and Labrador,mining,"Open-pit, concentrator",Cold Evergreen Needleleaf Forest,Fe concentrator + pellet plant,NaN,...,0.0,0.000000,NaN,NaN,NaN,NaN,0.0,0.000000,Open-pit mining and beneficiation at Carol Lake,NL-MAIN-dd723db4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,<NA>,GRP-0a2c0d69,NaN,Meadowbank complex,Nunavut,mining,"Open-pit, underground",NaN,Au–Ag free-milling,NaN,...,0.0,0.000000,NaN,NaN,NaN,NaN,0.0,17.667601,Open-pit and underground mining at Meadowbank ...,GRP-0a2c0d69
61,<NA>,GRP-0d911886,NaN,Porcupine complex,Ontario,mining,"Open-pit, underground",NaN,Au–Ag free-milling,NaN,...,0.0,0.000000,NaN,NaN,NaN,NaN,0.0,8.251949,Open-pit and underground mining at Porcupine c...,GRP-0d911886
62,<NA>,GRP-147b3123,NaN,Timmins Operation,Ontario,mining,"Underground, concentrator",NaN,Au–Ag free-milling,NaN,...,0.0,0.000000,NaN,NaN,NaN,NaN,0.0,4.218015,Underground mining and beneficiation at Timmin...,GRP-147b3123
63,<NA>,GRP-14bfbb82,NaN,Seabee Gold Operation,Saskatchewan,mining,"Underground, concentrator",NaN,Au–Ag free-milling,NaN,...,0.0,0.000000,NaN,NaN,NaN,NaN,0.0,1.230080,Underground mining and beneficiation at Seabee...,GRP-14bfbb82
64,<NA>,GRP-a13779f8,NaN,Snow Lake,Manitoba,mining,"Underground, concentrator",NaN,Au–Ag polymetallic,Particular production pattern. Check GHG cover...,...,69284.0,0.000000,NaN,NaN,NaN,NaN,0.0,32.978787,Underground mining and beneficiation at Snow Lake,GRP-a13779f8

In [8]:
# Normalized MetalliCan tables per ore processed
# energy_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/energy_df.csv')
# material_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/material_df.csv')
# biosphere_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/biosphere_df.csv')

In [9]:
# Normalized MetalliCan tables per ore processed
energy_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/energy_df.csv')
material_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/material_df.csv')
biosphere_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/biosphere_df.csv')
land_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/land_df.csv')
carbon_stock_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/carbon_stock_df.csv')

In [10]:
# Removing rows with value_normalized is NaN in the biosphere dfs
#biosphere_ore_df = biosphere_ore_df[~biosphere_ore_df['value_normalized'].isna()]
#biosphere_stream_df['value_normalized'] = biosphere_stream_df['value_normalized'] / 1e6

In [11]:
# For all the dfs, multiply the value_normalized to 10e3 to have values per kg
# energy_stream_df['value_normalized'] = energy_stream_df['value_normalized'] / 1e3
# material_stream_df['value_normalized'] = material_stream_df['value_normalized'] / 1e3
# material_stream_df['value_min_normalized'] = material_stream_df['value_min_normalized'] / 1e3
# material_stream_df['value_mean_normalized'] = material_stream_df['value_mean_normalized'] / 1e3
# material_stream_df['value_max_normalized'] = material_stream_df['value_max_normalized'] / 1e3
# biosphere_stream_df['value_normalized'] = biosphere_stream_df['value_normalized'] / 1e3
# land_stream_df['value_min_normalized'] = land_stream_df['value_min_normalized'] / 1e3
# land_stream_df['value_mean_normalized'] = land_stream_df['value_mean_normalized'] / 1e3
# land_stream_df['value_max_normalized'] = land_stream_df['value_max_normalized'] / 1e3

# Transform land_stream_df to have the same columns as biosphere_stream_df

In [12]:
# Drop rows where 'unit' = 'ha'
biosphere_stream_df = biosphere_stream_df[biosphere_stream_df['unit'] != 'ha']

In [13]:
def add_land_substance_name(df):
    """
    Add ecoinvent-style land use 'substance_name' column
    based on flow_type, npv and mining_processing_type.
    """

    import numpy as np

    out = df.copy()

    MANU_TYPES = {
        "Refinery",
        "Smelter, plant",
        "Smelter, refinery, plant",
    }

    is_manu = out["mining_processing_type"].isin(MANU_TYPES)

    out["substance_name"] = np.select(
        [
            out["flow_type"].eq("transformation_from"),
            out["flow_type"].eq("transformation_to") & is_manu,
            out["flow_type"].eq("transformation_to") & ~is_manu,
            out["flow_type"].eq("occupation") & is_manu,
            out["flow_type"].eq("occupation") & ~is_manu,
        ],
        [
            "Transformation, from " + out["npv"].astype(str),
            "Transformation, to manufacturing area",
            "Transformation, to mine area",
            "Occupation, manufacturing area",
            "Occupation, mine area",
        ],
        default=None,
    )

    return out

In [14]:
land_stream_df = add_land_substance_name(land_stream_df)

In [15]:
land_stream_df

,site_id,flow_type,functional_unit,normalization_key,allocation_factor,unit,activity_name,mining_processing_type,archetypes,npv,operation_periods,data_source,value_formula,parameter_distribution,value_normalized,reference_mass_unit,substance_name
0,BC-MAIN-3f490561,transformation_from,Cu concentrate,land_concentrate_economic,1.0,m2,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator",Cu Porphyry,Cold Evergreen Needleleaf Forest,NaN,MetalliCan,MetalliCan,NaN,0.008741,kg,"Transformation, from Cold Evergreen Needleleaf..."
1,BC-MAIN-3f490561,transformation_to,Cu concentrate,land_concentrate_economic,1.0,m2,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator",Cu Porphyry,Cold Evergreen Needleleaf Forest,NaN,MetalliCan,MetalliCan,NaN,0.008741,kg,"Transformation, to mine area"
2,BC-MAIN-3f490561,occupation,Cu concentrate,land_concentrate_economic,1.0,m2*year,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator",Cu Porphyry,Cold Evergreen Needleleaf Forest,NaN,MetalliCan,MetalliCan,NaN,0.174816,kg,"Occupation, mine area"
3,BC-MAIN-4724f4ba,transformation_from,Doré,land_concentrate_economic,1.0,m2,Open-pit mining at Elk,Open-pit,Au–Ag free-milling,Cold Evergreen Needleleaf Forest,NaN,MetalliCan,MetalliCan,NaN,167.650962,kg,"Transformation, from Cold Evergreen Needleleaf..."
4,BC-MAIN-4724f4ba,transformation_to,Doré,land_concentrate_economic,1.0,m2,Open-pit mining at Elk,Open-pit,Au–Ag free-milling,Cold Evergreen Needleleaf Forest,NaN,MetalliCan,MetalliCan,NaN,167.650962,kg,"Transformation, to mine area"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,MB-MAIN-e0a6250e,transformation_to,Ni concentrate,land_concentrate_economic,1.0,m2,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,Cold Evergreen Needleleaf Forest,NaN,Inference | land | open-pit regression,0.791 * ore_processed_t - 7.76e5,NaN,-0.000414,kg,"Transformation, to mine area"
185,MB-MAIN-e0a6250e,occupation,Ni concentrate,land_concentrate_economic,1.0,m2*year,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,Cold Evergreen Needleleaf Forest,NaN,Inference | land | open-pit regression,0.791 * ore_processed_t - 7.76e5,NaN,-0.008272,kg,"Occupation, mine area"
186,NL-MAIN-2d8801d6,transformation_from,Ni concentrate,land_concentrate_economic,1.0,m2,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,Cold Evergreen Needleleaf Forest,NaN,Inference | land | open-pit regression,0.791 * ore_processed_t - 7.76e5,NaN,-0.000088,kg,"Transformation, from Cold Evergreen Needleleaf..."
187,NL-MAIN-2d8801d6,transformation_to,Ni concentrate,land_concentrate_economic,1.0,m2,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,Cold Evergreen Needleleaf Forest,NaN,Inference | land | open-pit regression,0.791 * ore_processed_t - 7.76e5,NaN,-0.000088,kg,"Transformation, to mine area"
188,NL-MAIN-2d8801d6,occupation,Ni concentrate,land_concentrate_economic,1.0,m2*year,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,Cold Evergreen Needleleaf Forest,NaN,Inference | land | open-pit regression,0.791 * ore_processed_t - 7.76e5,NaN,-0.001752,kg,"Occupation, mine area"

In [16]:
carbon_stock_stream_df.rename(columns={"flow_type": "substance_name"}, inplace=True)

# Keeping only relevant columns

In [17]:
nrj_col = ['activity_name', 'functional_unit', 'site_id', 'subflow_type', 'unit', 'value_normalized']
material_col = ['activity_name', 'functional_unit', 'site_id', 'subflow_type', 'unit', 'value_normalized']
biosphere_col = ['activity_name', 'functional_unit', 'site_id', 'substance_name', 'unit', 'value_normalized']

In [18]:
# Create columns for biosphere_df
# biosphere_stream_df['value_min_normalized'] = ''
# biosphere_stream_df['value_mean_normalized'] = ''
# biosphere_stream_df['value_max_normalized'] = ''

In [19]:
energy_stream_df = energy_stream_df[nrj_col]
material_stream_df = material_stream_df[material_col]
biosphere_stream_df = biosphere_stream_df[biosphere_col]
land_stream_df = land_stream_df[biosphere_col]
carbon_stock_stream_df

,site_id,substance_name,functional_unit,normalization_key,allocation_factor,unit,activity_name,mining_processing_type,archetypes,data_source,value_formula,value_normalized,reference_mass_unit
0,BC-MAIN-3f490561,Carbon stock change,Cu concentrate,land_concentrate_economic,1.000000,t,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator",Cu Porphyry,MetalliCan,MetalliCan,1.442231e-04,kg
1,BC-MAIN-4724f4ba,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit mining at Elk,Open-pit,Au–Ag free-milling,MetalliCan,MetalliCan,3.258017e+00,kg
2,BC-MAIN-599152a0,Carbon stock change,Cu concentrate,land_concentrate_economic,1.000000,t,Open-pit mining and beneficiation at Copper Mo...,"Open-pit, concentrator",Cu Porphyry,MetalliCan,MetalliCan,1.948512e-04,kg
3,BC-MAIN-6b4800fe,Carbon stock change,Cu concentrate,land_concentrate_economic,0.976143,t,Open-pit mining and beneficiation at Gibraltar,"Open-pit, concentrator",Cu polymetallic,MetalliCan,MetalliCan,1.022212e-04,kg
4,BC-MAIN-6b4800fe,Carbon stock change,Mo concentrate,land_concentrate_economic,0.023857,t,Open-pit mining and beneficiation at Gibraltar,"Open-pit, concentrator",Cu polymetallic,MetalliCan,MetalliCan,4.331808e-04,kg
5,BC-MAIN-857b7b89,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,1.239937e+04,kg
6,BC-MAIN-8eb8be0d,Carbon stock change,Cu concentrate,land_concentrate_economic,0.917988,t,Open-pit mining and beneficiation at Red Chris,"Open-pit, concentrator",Au–Ag polymetallic,MetalliCan,MetalliCan,2.037789e-04,kg
7,BC-MAIN-8eb8be0d,Carbon stock change,Doré,land_concentrate_economic,0.082012,t,Open-pit mining and beneficiation at Red Chris,"Open-pit, concentrator",Au–Ag polymetallic,MetalliCan,MetalliCan,1.529616e+00,kg
8,BC-MAIN-aa76f6f2,Carbon stock change,Cu concentrate,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at New Afton,"Underground, concentrator",Cu Porphyry,MetalliCan,MetalliCan,2.532763e-05,kg
9,BC-MAIN-bf503b6b,Carbon stock change,Cu concentrate,land_concentrate_economic,0.978561,t,Open-pit mining and beneficiation at Highland ...,"Open-pit, concentrator",Cu polymetallic,MetalliCan,MetalliCan,1.579116e-04,kg
10,BC-MAIN-bf503b6b,Carbon stock change,Mo concentrate,land_concentrate_economic,0.021439,t,Open-pit mining and beneficiation at Highland ...,"Open-pit, concentrator",Cu polymetallic,MetalliCan,MetalliCan,6.691791e-04,kg
11,BC-MAIN-ed23117f,Carbon stock change,Cu concentrate,land_concentrate_economic,1.000000,t,Open-pit mining and beneficiation at Mount Mil...,"Open-pit, concentrator",Cu Porphyry,MetalliCan,MetalliCan,8.895702e-05,kg
12,MB-MAIN-e0a6250e,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,MetalliCan,MetalliCan,8.890003e-05,kg
13,MB-MAIN-e0a6250e,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,MetalliCan,MetalliCan,-4.852760e-06,kg
14,NL-MAIN-2d8801d6,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,MetalliCan,MetalliCan,5.202879e-06,kg
15,NL-MAIN-2d8801d6,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,MetalliCan,MetalliCan,-1.606304e-07,kg
16,NU-MAIN-8b0264c9,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,1.094688e-03,kg
17,ON-MAIN-0aadf28f,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,2.334599e+00,kg
18,ON-MAIN-1f126a43,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Macassa,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,2.787733e-01,kg
19,ON-MAIN-28f3f0fc,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Underground mining at Totten,Underground,Ni–Cu sulfide,MetalliCan,MetalliCan,1.269050e-05,kg
20,ON-MAIN-48fe2205,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Underground mining at Garson,Underground,Ni–Cu sulfide,MetalliCan,MetalliCan,6.304588e-05,kg
21,ON-MAIN-4e0734b5,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,3.268819e+00,kg
22,ON-MAIN-52224e1e,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Underground mining at Creighton,Underground,Ni–Cu sulfide,MetalliCan,MetalliCan,3.792791e-05,kg
23,ON-MAIN-687b8c8d,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Island,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,9.167036e+04,kg
24,ON-MAIN-6e9be24e,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,7.173308e-01,kg
25,ON-MAIN-7607a50e,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Young-...,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,1.871611e-01,kg
26,ON-MAIN-7f050560,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Red Lake,"Underground, concentrator",Au–Ag refractory,MetalliCan,MetalliCan,9.754846e-01,kg
27,ON-MAIN-8825d90d,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit mining and beneficiation at Magino,"Open-pit, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,1.599508e-01,kg
28,ON-MAIN-aeafbb59,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit mining and beneficiation at Detour Lake,"Open-pit, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,2.040416e-01,kg
29,ON-MAIN-cb85213a,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Eagle ...,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,7.690607e-02,kg
30,ON-MAIN-ed85ac94,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,and beneficiation at Strathcona,Concentrator,Ni–Cu sulfide,MetalliCan,MetalliCan,2.349336e-05,kg
31,ON-MAIN-f080c409,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Underground mining at Copper Cliff Complex (mine),Underground,Ni–Cu sulfide,MetalliCan,MetalliCan,5.934653e-04,kg
32,ON-MAIN-f4fc3276,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Sugar ...,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,5.259668e+04,kg
33,ON-MAIN-f8313ebd,Carbon stock change,Cu concentrate,land_concentrate_economic,0.723026,t,Underground mining and beneficiation at Kidd C...,"Underground, concentrator",Cu polymetallic,MetalliCan,MetalliCan,4.362570e-05,kg
34,ON-MAIN-f8313ebd,Carbon stock change,Zn concentrate,land_concentrate_economic,0.276974,t,Underground mining and beneficiation at Kidd C...,"Underground, concentrator",Cu polymetallic,MetalliCan,MetalliCan,1.630788e-05,kg
35,ON-MAIN-fefeaee4,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Mussel...,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,0.000000e+00,kg
36,QC-MAIN-02884fb5,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Westwo...,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,7.099816e-01,kg
37,QC-MAIN-5ce331b8,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Ni–Cu sulfide,MetalliCan,MetalliCan,1.168971e-06,kg
38,QC-MAIN-6dc537e6,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Éléonore,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,0.000000e+00,kg
39,QC-MAIN-9de9bb0d,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit mining and beneficiation at Kiena,"Open-pit, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,0.000000e+00,kg
40,QC-MAIN-a555d9b9,Carbon stock change,Nb concentrate,land_concentrate_economic,NaN,t,Underground mining and beneficiation at Niobec,"Underground, concentrator",Nb mine,MetalliCan,MetalliCan,NaN,kg
41,QC-MAIN-a555d9b9,Carbon stock change,Nb concentrate,land_concentrate_economic,NaN,t,Underground mining and beneficiation at Niobec,"Underground, concentrator",Nb mine,MetalliCan,MetalliCan,NaN,kg
42,QC-MAIN-a97821c0,Carbon stock change,Ni concentrate,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Raglan,"Underground, concentrator",Ni–Cu sulfide,MetalliCan,MetalliCan,0.000000e+00,kg
43,QC-MAIN-b86f7d07,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,8.731258e-01,kg
44,QC-MAIN-c0660aec,Carbon stock change,Cu concentrate,land_concentrate_economic,0.003859,t,Underground mining and beneficiation at Goldex,"Underground, concentrator",Au–Ag polymetallic,MetalliCan,MetalliCan,1.094412e-05,kg
45,QC-MAIN-c0660aec,Carbon stock change,Doré,land_concentrate_economic,0.996141,t,Underground mining and beneficiation at Goldex,"Underground, concentrator",Au–Ag polymetallic,MetalliCan,MetalliCan,8.214932e-02,kg
46,QC-MAIN-de3d8b7b,Carbon stock change,Pb concentrate,land_concentrate_economic,1.000000,t,Refining at Canadian Electrolytic Zinc Limited...,Refinery,Zn refinery,MetalliCan,MetalliCan,3.088282e-06,kg
47,QC-MAIN-e51eda66,Carbon stock change,Cu concentrate,land_concentrate_economic,0.097722,t,Underground mining and beneficiation at LaRonde,"Underground, concentrator",Au–Ag polymetallic,MetalliCan,MetalliCan,5.578557e-05,kg
48,QC-MAIN-e51eda66,Carbon stock change,Zn concentrate,land_concentrate_economic,0.065487,t,Underground mining and beneficiation at LaRonde,"Underground, concentrator",Au–Ag polymetallic,MetalliCan,MetalliCan,2.085341e-05,kg
49,QC-MAIN-e51eda66,Carbon stock change,Doré,land_concentrate_economic,0.836791,t,Underground mining and beneficiation at LaRonde,"Underground, concentrator",Au–Ag polymetallic,MetalliCan,MetalliCan,4.187405e-01,kg
50,QC-MAIN-e7e6a960,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Open-pit mining and beneficiation at Canadian ...,"Open-pit, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,3.363768e-01,kg
51,QC-MAIN-f9e41c2a,Carbon stock change,Doré,land_concentrate_economic,1.000000,t,Underground mining and beneficiation at Lamaque,"Underground, concentrator",Au–Ag free-milling,MetalliCan,MetalliCan,3.851569e-01,kg
52,YT-MAIN-44857446,Carbon stock change,Zn concentrate,land_concentrate_economic,0.621253,t,Underground mining and beneficiation at Keno H...,"Underground, concentrator",High-grade polymetallic Pb-Zn-Ag,MetalliCan,MetalliCan,3.151938e-04,kg
53,YT-MAIN-44857446,Carbon stock change,Pb concentrate,land_concentrate_economic,0.378747,t,Underground mining and beneficiation at Keno H...,"Underground, concentrator",High-grade polymetallic Pb-Zn-Ag,MetalliCan,MetalliCan,2.520490e-04,kg

In [20]:
# Put energy_df and material_df together, and biosphere_df and land_df together
technosphere_stream_df = pd.concat([energy_stream_df, material_stream_df], ignore_index=True)
biosphere_stream_df = pd.concat([biosphere_stream_df, land_stream_df, carbon_stock_stream_df], ignore_index=True)

In [21]:
# Remove rows where value_normalized is NaN
technosphere_stream_df = technosphere_stream_df[~technosphere_stream_df['value_normalized'].isna()]

In [22]:
# Add the province from the main_df to specify electricity location later
technosphere_stream_df = technosphere_stream_df.merge(production_df[['site_id', 'province']], on=['site_id'], how='left')
biosphere_stream_df = biosphere_stream_df.merge(production_df[['site_id', 'province']], on=['site_id'], how='left')

In [23]:
technosphere_stream_df

,activity_name,functional_unit,site_id,subflow_type,unit,value_normalized,province
0,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Acetylene,MJ,20.073290,British Columbia
1,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Aviation fuel,MJ,78960.609903,British Columbia
2,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Diesel,MJ,311863.781032,British Columbia
3,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Electricity consumption|Generated on-site,MJ,93681.235616,British Columbia
4,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Electricity consumption|Grid electricity,MJ,618213.376701,British Columbia
...,...,...,...,...,...,...,...
620,Underground mining and beneficiation at Timmin...,Doré,GRP-147b3123,Tailings|Gold,t,-373.160269,Ontario
621,Underground mining and beneficiation at Seabee...,Doré,GRP-14bfbb82,Tailings|Gold,t,-99.179545,Saskatchewan
622,Underground mining and beneficiation at Snow Lake,Cu concentrate,GRP-a13779f8,Tailings|Gold,t,-0.006414,Manitoba
623,Underground mining and beneficiation at Snow Lake,Zn concentrate,GRP-a13779f8,Tailings|Gold,t,-0.002398,Manitoba
624,Underground mining and beneficiation at Snow Lake,Doré,GRP-a13779f8,Tailings|Gold,t,-48.146845,Manitoba

# Map MetalliCan flows to EI and RI flows

In [24]:
from utils.conversion_functions import map_technosphere_to_ecoinvent, map_biosphere_to_ecoinvent
from utils.constants import CA_provinces

## Technosphere flows

In [25]:
mapping_technosphere_ri = pd.read_excel(r'data/Mappings/MAPPINGS_RI.xlsx', sheet_name='technosphere')
mapping_technosphere_ei = pd.read_excel(r'data/Mappings/MAPPINGS_EI.xlsx', sheet_name='technosphere')

In [26]:
# Apply the function
mapped_technosphere_ri_df = map_technosphere_to_ecoinvent(technosphere_stream_df, mapping_technosphere_ri, CA_provinces)
mapped_technosphere_ei_df = map_technosphere_to_ecoinvent(technosphere_stream_df, mapping_technosphere_ei, CA_provinces)

⚠️ Les flux suivants n'ont pas trouvé de correspondance dans Ecoinvent:
 - Other
 - Tailings|Other
⚠️ Les flux suivants n'ont pas trouvé de correspondance dans Ecoinvent:
 - Other
 - Tailings|Other

In [27]:
# Drop rows where ecoinvent_flow_name is "No mapping" and Amount is NaN for now
#mapped_technosphere_ore_df = mapped_technosphere_ore_df[(mapped_technosphere_ore_df["Activity"] != "No mapping") & (~mapped_technosphere_ore_df["Amount"].isna())]
mapped_technosphere_ri_df = mapped_technosphere_ri_df[(mapped_technosphere_ri_df["Activity"] != "No mapping")]
mapped_technosphere_ei_df = mapped_technosphere_ei_df[(mapped_technosphere_ei_df["Activity"] != "No mapping")]

In [28]:
technosphere_col_for_lci = ['site_id', 'activity_name', 'functional_unit', 'Amount', 'Amount_min', 'Amount_mean', 'Amount_max', 'Activity', 'Product', 'Unit', 'Location', 'Database']

In [29]:
#mapped_technosphere_ore_df = mapped_technosphere_ore_df[technosphere_col_for_lci]
mapped_technosphere_ri_df = mapped_technosphere_ri_df[technosphere_col_for_lci]
mapped_technosphere_ei_df = mapped_technosphere_ei_df[technosphere_col_for_lci]

## Biosphere flows mapping

In [30]:
mapping_biosphere_ri = pd.read_excel(r'data/Mappings/MAPPINGS_RI.xlsx', sheet_name='biosphere')
mapping_biosphere_ei = pd.read_excel(r'data/Mappings/MAPPINGS_EI.xlsx', sheet_name='biosphere')

In [31]:
#mapped_biosphere_ore_df = map_biosphere_to_ecoinvent(biosphere_ore_df, mapping_biosphere, CA_provinces)
mapped_biosphere_ri_df = map_biosphere_to_ecoinvent(biosphere_stream_df, mapping_biosphere_ri, CA_provinces)
mapped_biosphere_ei_df = map_biosphere_to_ecoinvent(biosphere_stream_df, mapping_biosphere_ei, CA_provinces)

Index(['activity_name', 'functional_unit', 'site_id', 'substance_name', 'unit',
       'value_normalized', 'normalization_key', 'allocation_factor',
       'mining_processing_type', 'archetypes', 'data_source', 'value_formula',
       'reference_mass_unit', 'province', 'Type', 'substance_id',
       'compartment_name', 'release_pathway', 'flow_direction',
       'MetalliCan_unit', 'DB_to_map', 'Flow name', 'Compartments', 'Unit',
       'Comment', 'Alternatives'],
      dtype='object')
⚠️ 1 biosphere flows could not be mapped to Ecoinvent:
   - PFCs
⚠️ No conversion defined for tco2eq → nan (flow: PFCs)
✅ Mapped 17609 biosphere flows (118 unique flows).
Index(['activity_name', 'functional_unit', 'site_id', 'substance_name', 'unit',
       'value_normalized', 'normalization_key', 'allocation_factor',
       'mining_processing_type', 'archetypes', 'data_source', 'value_formula',
       'reference_mass_unit', 'province', 'Type', 'substance_id',
       'compartment_name', 'release_pathway', 'flow_direction',
       'MetalliCan_unit', 'DB_to_map', 'Flow name', 'Compartments', 'Unit',
       'Comment', 'Alternatives'],
      dtype='object')
⚠️ 1 biosphere flows could not be mapped to Ecoinvent:
   - PFCs
⚠️ No conversion defined for tco2eq → nan (flow: PFCs)
✅ Mapped 17609 biosphere flows (54 unique flows).

In [32]:
# Drop rows where ecoinvent_flow_name is "No mapping" and Amount is NaN for now
#mapped_biosphere_ore_df = mapped_biosphere_ore_df[(mapped_biosphere_ore_df["Flow Name"] != "No mapping") & (~mapped_biosphere_ore_df["Amount"].isna())]
mapped_biosphere_ri_df = mapped_biosphere_ri_df[(mapped_biosphere_ri_df["Flow Name"] != "No mapping") & (~mapped_biosphere_ri_df["Amount"].isna())]
mapped_biosphere_ei_df = mapped_biosphere_ei_df[(mapped_biosphere_ei_df["Flow Name"] != "No mapping") & (~mapped_biosphere_ei_df["Amount"].isna())]

In [33]:
biosphere_col_for_lci = ['site_id', 'activity_name', 'functional_unit', 'Amount', 'Unit', 'Flow Name', 'Compartments', 'Database']

In [34]:
#mapped_biosphere_ore_df = mapped_biosphere_ore_df[biosphere_col_for_lci]
mapped_biosphere_ri_df = mapped_biosphere_ri_df[biosphere_col_for_lci]
mapped_biosphere_ei_df = mapped_biosphere_ei_df[biosphere_col_for_lci]

In [35]:
# Add province and commodities from NRCan to production table
#mapped_biosphere_ore_df = mapped_biosphere_ore_df.merge(production_df[['site_id', 'province', 'commodities']], on=['site_id'], how='left')
mapped_biosphere_ri_df = mapped_biosphere_ri_df.merge(production_df[['site_id', 'province', 'commodities']], on=['site_id'], how='left')
mapped_biosphere_ei_df = mapped_biosphere_ei_df.merge(production_df[['site_id', 'province', 'commodities']], on=['site_id'], how='left')

# LCI creation

In [36]:
from core.lci_database_builder import LCIDatabaseBuilder

## Regioinvent

In [37]:
# Step 1 — initialize the builder
builder_uo = LCIDatabaseBuilder(db_name='metallican_lci_ri', project_name='metallican')

📂 Active Brightway project: metallican
✅ Using existing database 'metallican_lci_ri'.

In [38]:
# Step 2 — create the activity shells from the main dataframe
builder_uo.build_lci_entries(df=mapped_biosphere_ri_df)
print(len(builder_uo.lcis))

✅ Created 59 base LCI activities with production exchanges.
59

In [39]:
# Step 3a — Populate with the technosphere exchanges
builder_uo.populate_technosphere_exchanges(technosphere_df=mapped_technosphere_ri_df)

⚙️ Populating technosphere exchanges
   ✅ Cached 218246 activities from Regioinvent
   ✅ Cached 20769 activities from ecoinvent-3.10-cutoff regionalized
✅ Added 741 technosphere exchanges.

In [40]:
# Step 3b — Populate with the biosphere exchanges
builder_uo.populate_biosphere_exchanges(biosphere_df=mapped_biosphere_ri_df)

🌱 Populating biosphere exchanges
   ✅ Cached 4362 biosphere flows from biosphere3
   ✅ Cached 110559 biosphere flows from biosphere3_spatialized_flows
✅ Added 12415 biosphere exchanges.

In [41]:
# Step 4 - Consolidate duplicate flows
builder_uo.consolidate_exchanges()

🧮 Consolidation: 13215 → 1910 exchanges (summed duplicates).

In [42]:
builder_uo.write_to_database()

🧱 Writing 59 activities to database 'metallican_lci_ri'...
✅ Database 'metallican_lci_ri' processed successfully with 59 activities.

## Ecoinvent

In [43]:
# Step 1 — initialize the builder
builder_uo = LCIDatabaseBuilder(db_name='metallican_lci_ei', project_name='metallican')

📂 Active Brightway project: metallican
🆕 Database 'metallican_lci_ei' created.

In [44]:
# Step 2 — create the activity shells from the main dataframe
builder_uo.build_lci_entries(df=mapped_biosphere_ei_df)
print(len(builder_uo.lcis))

✅ Created 59 base LCI activities with production exchanges.
59

In [45]:
# Step 3a — Populate with the technosphere exchanges
builder_uo.populate_technosphere_exchanges(technosphere_df=mapped_technosphere_ei_df)

⚙️ Populating technosphere exchanges
   ✅ Cached 20769 activities from ecoinvent-3.10-cutoff
✅ Added 716 technosphere exchanges.
⚠️ 25 exchanges could not be matched:
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-ON)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-NU)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-ON)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-ON)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-ON)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-ON)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-ON)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-BC)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-MB)
   - market for cement, unspecified (ecoinvent-3.10-cutoff, CA-NF)
   ... and 15 more.

In [46]:
# Step 3b — Populate with the biosphere exchanges
builder_uo.populate_biosphere_exchanges(biosphere_df=mapped_biosphere_ei_df)

🌱 Populating biosphere exchanges
   ✅ Cached 4362 biosphere flows from biosphere3
✅ Added 12415 biosphere exchanges.

In [47]:
# Step 4 - Consolidate duplicate flows
builder_uo.consolidate_exchanges()

🧮 Consolidation: 13190 → 1850 exchanges (summed duplicates).

In [48]:
builder_uo.write_to_database()

🧱 Writing 59 activities to database 'metallican_lci_ei'...
✅ Database 'metallican_lci_ei' processed successfully with 59 activities.